### ISSUE TITLE
Provide option to NOT print handles/names on hoodies

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2015.cascadiajs.com#1]
(Copied from CJS 2014 issues)

Some people love having their handles/names on their hoodies. Some people hate it. For CJS 2015, please allow an option for attendees to have a generic hoodie without any name/handle information on it.

Thanks!

**Comment by jdalton** [comment]
I heard the hoodies didn't have aliases this year so wanted to throw my :+1: for them.

FWIW having the aliases printed on the hoodies was one of the more interesting conference swags I've ever received. I wore the 2012 hoodie out and was delighted that Cascadia offered it again in 2014. It's still apart of my daily outfit. I've had a great experience with it and get comments on it from time to time from other devs wanting to know where I got it.

**Comment by dtex** [comment]
Oooh, having handles does sound cool but I can respect making it optional. I'm with @jdalton

**Comment by jdalton** [comment]
@dtex
> I can respect making it optional. I'm with @jdalton

Optional is great.
Something like a blank text field that allows arbitrary text (with the alias as a hint).

**Comment by hackygolucky** [comment]
YES! For the most part, the organizing staff really WANTED the names on the
sleeve. We were going to make it optional per feedback from last year with
people not wanting it, but logistically it is more work/costs more for us
to do. When tasks came down to the timecrunch, it was held under
nice-to-have. We will try again next year!
