### ISSUE TITLE
Talk: Sensory Substitution as an Way to Encode Messages

### ISSUE THREAD

**Issue by ednapiranha** [cascadiajs/2015.cascadiajs.com#103]
# Sensory Substitution as an Way to Encode Messages

* Name      : Jen Fong-Adwent
* Location  : Portland, OR
* Email     : jen@theoperator.org
* GitHub    : [ednapiranha](https://github.com/ednapiranha)

## The story you'd like to tell

As children, we may have experienced the fun in trading secret notes using a simple decoder or lemon juice over heat. We were able to switch context and learn to change our methods on a weekly basis - as adults, we're not as likely to do this. How can we increase our [brain plasticity](http://en.wikipedia.org/wiki/Neuroplasticity) to be able to switch context and learn quickly like we did as children? Can we also experiment with obscured communications like the simple decoder but through [sensory substitution](http://en.wikipedia.org/wiki/Sensory_substitution) via something simple like sound to word/concept/meaning association?

We'll look at a concept application in Node that will demonstrate how both children and adults can learn to rewire their brains on a frequent basis to unlearn "stuck" associations from the past, which will enable better one-to-one communication, human interaction and creativity.

Also remember to DRINK MORE OVALTINE.

## Speaker Bio

<img src="http://scontent-b-sea.cdninstagram.com/hphotos-xfa1/t51.2885-15/10946594_652799261515739_473353803_n.jpg" width="150">

I'm Jen, I work at Mozilla on Developer Tools and have made [some stuff](http://ednapiranha.com/about.html) in the past.

**Comment by KatieK2** [comment]
Did you mean to close this issue? If you're still interested in giving this talk, we'd like for it to be an open issue. Let me know you'd like me to re-open it.  Thanks!

**Comment by ednapiranha** [comment]
Yep, I think I'm going to close it for now thanks :)
