### ISSUE TITLE
That JS Looks Good on You: Wearables and JavaScript

### ISSUE THREAD

**Issue by joe-crick** [cascadiajs/2015.cascadiajs.com#107]
# That JS Looks Good on You: Wearables and JavaScript

* Name      : Joseph Crick
* Location  : Seattle, USA
* Email     : joe@bitovi.com
* GitHub    : [joe-crick](https://github.com/joe-crick)

## The Talk

The Pebble watch is making a splash. The Apple Watch is expected in April (2015). Wearables are creating new opportunities for companies and developers to reach audiences with a wide variety of needs and interests. JavaScript is coming right along with them. 

In this talk, I’ll explore some of the possibilities that wearables promise, as we look into the current state of programming wearables with JavaScript using the Pebble Watch. Together, we’ll investigate ways you can integrate a wearable application with web-based applications and services to create interesting and useful experiences.

## Speaker Bio

![joseph_081](https://cloud.githubusercontent.com/assets/5924684/6034109/b80ee52a-abd3-11e4-9902-1eefa7aee61c.JPG)

Joseph Crick is a developer at [Bitovi](http://www.bitovi.com). When he’s not traveling the world performing feats of JavaScript, he hunkers down to take it easy in an undisclosed location. He has been “The Front-end Dev” at several companies, before happily settling at Bitovi—where he is now a productive member of a thriving JS tribe.

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. This is an interesting proposal! It would be helpful to know if this is more about code that **interacts** with the Pebble, or is it more about writing applications to run **on** the Pebble.
Looking forward to hearing from you, and thanks for your proposal!
