### ISSUE TITLE
De-coupling data from presentation

### ISSUE THREAD

**Issue by alexisabril** [cascadiajs/2015.cascadiajs.com#112]
# De-coupling data from presentation

* Name      : Alexis Abril
* Location  : Dallas, TX, USA
* Email     : alexis@bitovi.com
* Twitter   : [@alexisabril](https://twitter.com/alexisabril)
* GitHub    : [alexisabril](https://github.com/alexisabril)
* Url(s)    : [alexisabril.com](http://alexisabril.com)

## The story you'd like to tell

Rediscover the "M" in MV* approaches as we dive into what logic belongs in a data layer. Validation, inheritance and REST abstractions are a few points we will address in making your business and presentation layers lighter, more modular and easier to maintain.

## Speaker Bio

![](http://alexisabril.com/images/avatar.png)

Alexis Abril is a developer for Bitovi, a JavaScript consulting firm based in Chicago, IL. A UT Dallas alum, Alexis is focused on education within the community and is the organizer for the DallasJS meetup. He has spoken at various conferences and trainings around the globe, and is a lover of all things JavaScript!

**Comment by ryan-roemer** [comment]
Hi @alexisabril -- I'm on the Server JS day talk review committee. I was hoping that you could add a few more details about what your technical discussion will entail. Also, maybe comment on things with respect to the "M" we know and love in some common JS frameworks? And, are you going to be talking about client / server / both "MV" apps?

**Comment by alexisabril** [comment]
Hey @ryan-roemer, I'd be happy to! The examples and core of the talk was primarily based in client side MV patterns, however the concepts are the focus. I would say if I did not have any concrete implementations planned, this could be a theory talk, allowing for both server and client applications(the talk still does, but the examples wouldn't apply).

This started with an observation I've had over the past couple of years as more companies move to adopt client MV* frameworks. There seems to be a blur, disconnect or misunderstanding between the concept of a ViewModel and a Data Model/Entity. Building a rich data layer, on the server or the client, makes building the rest of an application much easier to digest and in some scenarios, even trivial.

A simple example could be a data entity that has a capability to "restore" it's property values to some original state. This behavior would be very helpful in the case of a "cancel" button on a page and is typically where that functionality ends up living(in the business logic/controller layer). However, the ability to restore is something that could exist much lower, without knowledge of any specific business process. It then becomes re-usable, generic and even something your business specific entities can inherit/extend from.

My examples would be in jQuery/CanJS, not for favoritism/APIs/etc, but rather that is just where my experience happens to lie.
