### ISSUE TITLE
Talk: Isomorphic application architecture with Flux and React

### ISSUE THREAD

**Issue by mdressman** [cascadiajs/2015.cascadiajs.com#115]
# Isomorphic application architecture with Flux and React

* Name      : Matthew Dressman
* Location  : Seattle, WA
* Email     : matthewd@porch.com
* Twitter   : [@mdressman](http://twitter.com/mdressman)
* GitHub    : [mdressman](http://github.com/mdressman)
* Url(s)    : [porch.com](http://porch.com)

## The story you'd like to tell

Isomorphic JavaScript is code that can run both on the server and in the client. It's one of those magical phrases these days, but is it really worthwhile to design your application architecture in this style or is it a shiny new trend that's not worth the cost? 

In this talk, we'll explore the concepts of isomorphic JavaScript, its pros and cons, and the ~~challenges~~ opportunities you'll face designing your application architecture. Topics will include server-side rendering, data fetching, routing, building and packaging, and more.

I'll share our experiences building an isomorphic application with React and Flux at [Porch.com](http://porch.com) and the reasons that ultimately led us to adopt Yahoo's open-source [Fluxible](http://fluxible.io) implementation.

*"The dream of the 90s is alive"*

## Speaker Bio

![](http://dbfestival.com/assets/mdressman.png)

I'm a full-stack software engineer at [Porch.com](http://porch.com), focused on creating engaging user experiences with React and Flux.

**Comment by HenryrosePorch** [comment]
This is cool, i think people will be stoked on this topic.

**Comment by jay-porch** [comment]
Agree - it's a pretty huge deal to be able to choose from client to server-side rendering without any retooling.
