### ISSUE TITLE
Flexbox: Coming to a Browser Near You

### ISSUE THREAD

**Issue by jen4web** [cascadiajs/2015.cascadiajs.com#116]
# Flexbox: Coming to a Browser Near You

* Name      : Jen Kramer
* Location  : Arlington, MA, USA
* Email     : jen@jenkramer.org
* Twitter   : [www.twitter.com/jen4web]
* GitHub    : [@jen4web]
* Url(s)    : [www.jenkramer.org]

CSS layouts are a pain in the neck. Fortunately, the flexible box layout, also known as FlexBox, is almost ready for use in production websites. Take a quick look at FlexBox, including what it is, how it's configured, where it's useful, its terminology, and browser support. Get a jump on this future of web layouts!

## Speaker Bio
For more than a dozen years, Jen Kramer has been educating clients, colleagues, friends and graduate students about the meaning of a "quality website." Jen is a lynda.com author with 24 published titles, including the popular "Up and Running with Bootstrap 3", "Web Semantics", and "Up and Running with Foundation 5". Jen currently offers in-person and online courses through Harvard Extension and National University. She is also offers private tutoring, customized classroom training, and consulting.

![jen300sq](https://cloud.githubusercontent.com/assets/2278188/6086601/35f064ac-ae11-11e4-9cd9-86aa05a4ce50.jpg)

**Comment by astearns** [comment]
Jen, I've seen a number of Flexbox talks (and given a couple). One thing I've missed is a good story for how to progressively enhance a non-flexbox site made for older browsers with a flexbox layout for newer browsers. Is this something you'd cover?

**Comment by jen4web** [comment]
Hi, I've not started to put together the talk yet.
