### ISSUE TITLE
Talk: Make 8-bit Music in your Browser

### ISSUE THREAD

**Issue by emkay** [cascadiajs/2015.cascadiajs.com#119]
# Make 8-bit Music in your Browser

* Name      : Michael Matuzak
* Location  : Los Angeles, CA, USA
* Email     : mmatuzak@gmail.com
* Twitter   : [@mmatuzak](https://twitter.com/mmatuzak)
* GitHub    : [emkay](https://github.com/emkay)
* Url(s)    : [lambdaphant.com](http://lambdaphant.com)

## How my love of Nintendo and music was brought together with javascript.

My talk will explore the world of creating music with your browser and the options that are available, such as [`webaudio`](https://github.com/NHQ/webaudio). Will also cover bits of the web audio api, and how to get that authentic 8-bit sound. I have a super cool idea for a web-rtc demo that would involve volunteers to participate during the talk. That part is subject to change depending on how things go.

## Speaker Bio

<img alt="Mikes Avatar" height="256" src="https://avatars1.githubusercontent.com/u/1327?v=3&amp;s=460" width="256">

I work for Yahoo, co-organize [js.la](http://js.la), and hack on Nintendos and stuff.

**Comment by GregBulmash** [comment]
Hi, I'm on the browser-day committee and we've been asked to reach out to
proposers with questions before the CFP closes.

Are there particular libraries you'll demonstrate or is this raw Web Audio
API stuff?
Are there any particular 8-bit game themes you're going to demo?

**Comment by emkay** [comment]
I was planning on using the raw Web Audio API, but I've also played around with the `baudio` and `webaudio` module which has the same API as `baudio`, but works in the browser.

Not sure that I will demo any specific game themes, it might just be either some stuff I throw together, or a much cooler web-rtc demo that I have an idea for.

Of course this is subject to change, as I haven't built some of that stuff yet. Please let me know if you have any more questions.

**Comment by KatieK2** [comment]
Hi @emkay; I'm also with the review committee. Thanks for the clarifications! I do recommend that you update the main proposal body (the issue) with these additional details because it's the only thing that - when we're reading and evaluating all 200 talks - everyone is guaranteed to see. ;)

**Comment by emkay** [comment]
Updated. Thanks for the suggestion @KatieK2!
