### ISSUE TITLE
CFP open submissions time and deadline

### ISSUE THREAD

**Issue by hackygolucky** [cascadiajs/2015.cascadiajs.com#12]
Working backwards and given time constraints in prior years, it looks like the Call will be coming soon!

January 15th   45-day submission window**
March 8th       1-month window for final review by committee
April 8th          3-month notice to acceptances/rejections
**CJS 2015, July 8-10**

**allows for added benefit of early submissions to receive feedback and improve for resubmission.

Does this sound about right, @crtr0?

Cross-referencing with #8 as these organizers/curators will have to be committed by then and helping with this effort!

**Comment by jden** [comment]
I went through and read the timeline in the readme, and it LGTM. Now that I'm back working at a regular desk, it's super much easier for me to stay on top of github issues. Also, Fridays are an excellent time to get ahold of me since I'm not working those days. Onward Cascadia!
