### ISSUE TITLE
How I Lost 20 Lbs on Github: An Open Source Productivity Life Hack

### ISSUE THREAD

**Issue by una** [cascadiajs/2015.cascadiajs.com#121]
# How I Lost 20 Lbs on Github And Became Really, Really, Really Productive

* Name      : Una Kravets
* Location  : Austin, TX, USA
* Email     : una.kravets@gmail.com
* Twitter   : [@una](http://twitter.com/una)
* GitHub    : [una](http://github.com/una)
* Url(s)    : [My Blog](http://una.github.io), [Blog Post on the Topic](http://una.github.io/personal-goals-guide/), [The Repo Mentioned](https://github.com/una/personal-goals)

## The Story

It’s really difficult not to get overwhelmed as a web developer. The more you learn about code, and the deeper you dive, the more you realize you don’t know. There’s so little time and so much to do! Sometimes we start on one task and forget about it when the next shiny new thing comes along (probably about a week). What’s this, another new framework? Might this be next big thing? But wait, I still haven’t tried out A, B, or C. I’m so behind!

It's insane how much we have to balance as builders of the modern web.

Luckily, we can leverage the tools we already use every day to help us accomplish our goals. For over 18 weeks (as of this proposal, I don't intend to stop), I’ve kept a dutifully maintained open source list of goals and accomplishments on Github. In fact, it has developed into a full system, including specified folders, terminal aliases, and weekly planning reviews. Basically, open sourcing my personal goals has made me really, really, really productive and taught me time management skills.

In this talk, I’ll teach the audience how to leverage development tools to achieve their own personal goals — whether that be running a 10K, learning a new language, or developing a new project every other week. I’ll talk about my personal experiences, why I decided to go with this approach, the potential of going overboard, and ways that the system has changed and adapted from its instantiation. This talk will be filled with stories about the struggle to stay “new” in an industry that changes week to week, and leave the audience with the technical know-how and action steps for setting up their own systems.

## Speaker Bio

![](http://unakravets.com/una-256.png)

My name is Una (it’s pronounced you-na, like unicorn, or Unicron for you Transformers fans). I’m a front end developer with a design degree (although I spent most of my weekends in college at hackathons). Currently, I'm working in Austin, Texas in the IBM Design studio on the Watson Core and Visioneering teams. While living in DC, I co-founded the DC Sass Meetup, and after moving to Austin, helped start the ATXSass Meetup. As a member of the Design Open team, I’m also working to foster designer participation in the open source community. I'm a performance nerd, audiobook junkie, and an all-around crafty lady.

**Comment by blakmatrix** [comment]
:+1:
