### ISSUE TITLE
Art Class 404 - Day 1 - Spare the art, spoil the nth-child()

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [cascadiajs/2015.cascadiajs.com#129]
# Art Class 404 - Day 1

* Name      : John Brown
* Location  : Portland, OR
* Email     : thisisjohnbrown@gmail.com
* Twitter   : [@thisisjohnbrown](http://twitter.com/thisisjohnbrown)
* GitHub    : [thisisjohnbrown](http://github.com/thisisjohnbrown)
* Url(s)    : [thisisjohnbrown.com](http://thisisjohnbrown.com)

## Spare the art, spoil the nth-child()

You’re working with CSS every day. You’re making the unstyled structure of the web look amazing. You’re utilizing interesting techniques to match the comps you got from the design team. But when was the last time you created something unique, beautiful, and personal?

Creative coding isn’t just for someone with a deep understanding of fractals or an MFA. With a bit of Sass and Haml and a desire to explore, you can create some amazing generative art. Not only is the destination amazing, the journey is great as well, because in your quest to create, you’ll learn new techniques that will help you in your regular work. The next time a project comes up, you’ll get to apply your new found knowledge of nested animations and blend modes to make the web pop! 

So let’s talk about code art! When you leave, you’ll be inspired to create delightfully styled and elegantly animated pieces of art.

***

Art Class 404 is a triptych of talks I am submitting with the central theme of creative coding. Each will build on the previous day and speak specifically to that day’s theme (CSS, Javascript, Server). However, each will be approachable for attendees that don’t come for all three days. If time doesn’t allow for all, any of the three could be chosen to have on its own.

Each talk includes:

*	ways to get started in that particular area of creative coding.
*	some personal project successes and failures
*	what some other amazing people are doing
*	homework! (due date: CascadiaJSFest 2016)

## This is John Brown:

![](http://thisisjohnbrown.com/img/johnBrown600x600.png)

John Brown is a Swiss Army developer. He co-runs the [PDX Creative Coders](meetup.com/PDX-Creative-Coders/) group and is active in the code art community with pieces in galleries and physical installations. He is on a quest to get all developers to try making art with their code. His work is usually an interplay between physical and digital, with heavy hits of interactivity. For his day job, John Brown is a Technical Director at Instrument, where he's figuring out new ways to use existing technologies and unheard of ways to use emerging technologies.

**Comment by una** [comment]
code art sounds like a lot of fun :)
