### ISSUE TITLE
CSS vs pre-processors like Sass, Less and Stylus?

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2015.cascadiajs.com#13]
With CJS 2015's new CSS day, how do we feel about pre-processors vs. vanilla CSS? 

I'm willing to bet we'll get proposals from the Sass community. ;)  While the focus should remain on vanilla CSS, if the proposals are strong enough we could consider something along the lines of "The Sass Hour".

**Comment by KatieK2** [comment]
Based on all the feedback here and at other places, here is some language that I propose to be used in a FAQ for the CFS:

**What about Sass / CoffeeScript / another compiler or framework?**
The core focus of CascadiaJS is on vanilla JavaScript, standard CSS and plain old Node. This means that our content will be useful to the widest possible audience. The reality of modern development is that most developers utilize workflow accelerators like compilers and frameworks, but nothing can be done without understanding the core technologies. Thus to be successful, proposals which focus on a single facet of CSS/JS/Node will need to be very strong in comparison to a more general proposal.

(Please feel free to modify, fold and spindle as needed.)

**Comment by kennethormandy** [comment]
I liked this approach on the [JS Fest Oakland CFP](https://github.com/jsfest/oakland-cfp):

> ### What makes a good talk
>
> Don't talk about **a** technology, tell the story of what you **did** with that technology.
>
> Nobody ever left a conference talk with enough information in their head to write a program from what they learned. For obvious practical reasons people learn and continue to follow documentation while writing software. Don't try to teach people what is already in the documentation, tell them a story that makes them care enough to follow up with that technology.

I think something along these lines this deals with the concern better: it’s not that people might submit talks using Sass, it’s that they might focus on how it’s done with Sass instead of the problem that’s actually being tackled.
