### ISSUE TITLE
Art Class 404 - Day 3 - There’s no art like Node art

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [cascadiajs/2015.cascadiajs.com#131]
# Art Class 404 - Day 3

* Name      : John Brown
* Location  : Portland, OR
* Email     : thisisjohnbrown@gmail.com
* Twitter   : [@thisisjohnbrown](http://twitter.com/thisisjohnbrown)
* GitHub    : [thisisjohnbrown](http://github.com/thisisjohnbrown)
* Url(s)    : [thisisjohnbrown.com](http://thisisjohnbrown.com)

## There’s no art like Node art

Just because it’s on the backend doesn’t mean it can’t be beautiful. The backend developer is possibly the best suited for creative coding. Frontend developers get WebGL and animation frameworks, sure, but backenders get to connect APIs to physical devices, render infinite images from headless browsers, drive LEDs, and more. So many explorational paths are at your fingertips.

Does that sound daunting? Well, there are over 100,000 packages in npm, which can be combined with a bit of thought and artistic thinking to make interesting and unique entities. If you want to do something that deconstructs images, there are great image libraries to unpack gif, jpg, and png. There are modules for controlling physical sensors, projectors, phones, printers, and more. Converting data into art or art into data, all this can be done without reinventing the wheel.

You can be the glue that binds together the frontend pieces or run completely on your own. I’ll show you some great code art projects and talk about how the backend either ran the entire show ([@AvatarGlitch](http://twitter.com/avatarglitch)) or was a critical piece to making art on the frontend ([uncontext](http://uncontext.com)). Take a break from making the web work and make something beautiful for the web!

***

Art Class 404 is a triptych of talks I am submitting with the central theme of creative coding. Each will build on the previous day and speak specifically to that day’s theme (CSS, Javascript, Server). However, each will be approachable for attendees that don’t come for all three days. If time doesn’t allow for all, any of the three could be chosen to have on its own.

Each talk includes:

*	ways to get started in that particular area of creative coding.
*	some personal project successes and failures
*	what some other amazing people are doing
*	homework! (due date: CascadiaJSFest 2016)

## This is John Brown:

![](http://thisisjohnbrown.com/img/johnBrown600x600.png)

John Brown is a Swiss Army developer. He co-runs the [PDX Creative Coders](meetup.com/PDX-Creative-Coders/) group and is active in the code art community with pieces in galleries and physical installations. He is on a quest to get all developers to try making art with their code. His work is usually an interplay between physical and digital, with heavy hits of interactivity. For his day job, John Brown is a Technical Director at Instrument, where he's figuring out new ways to use existing technologies and unheard of ways to use emerging technologies.

**Comment by ryan-roemer** [comment]
Hi @ThisIsJohnBrown -- I'm on the Server JS day talk review committee. Could provide a little more details / examples of what you mean by "packages in npm, which can be combined ... to make interesting and unique entities" and perhaps some exemplary code art projects? Thanks!

**Comment by ThisIsJohnBrown** [comment]
Hey, @ryan-roemer! Sorry for the delay, never saw the notification for this.

What I mean by that quote is that anything someone wants to do with code from an artistic sense probably already has a jumping off point in npm. If you want to do something that deconstructs images, there are great image libraries to unpack gif, jpg, and png. There are modules for controlling physical sensors, projectors, phones, printers, and more. People shouldn't be afraid that a project is too daunting, because they don't need to write all the code to connect pieces together, much like we don't write a framework from scratch whenever we start a new website.

From a server perspective for code art, I would point to my personal projects like [@AvatarGlitch](http://twitter.com/avatarglitch) and other twitterbots for pure server output but also things like [RaveWave] (https://www.youtube.com/watch?v=kovJHzQNsg0&feature=youtu.be&t=22m4s) or [uncontext](http://uncontext.com). These are varying levels of server side engagement from date creation to content creation.

If I get the chance to speak to the ServerJS group, I have a few projects that are in the works I would finish up and present on, as well.

**Comment by KatieK2** [comment]
Hi @ThisIsJohnBrown! I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thanks! :)

**Comment by ThisIsJohnBrown** [comment]
Thanks, @KatieK2! I added some of that into the abstract.
