### ISSUE TITLE
Talk: exploring fractals in CSS

### ISSUE THREAD

**Issue by pixelass** [cascadiajs/2015.cascadiajs.com#132]
# Exploring Fractals in CSS

* Name      : Gregor Adams
* Location  : Munich Germany
* Email     : greg@pixelass.com
* Twitter   : [@GregorAdams](https://twitter.com/GregorAdams)
* GitHub    : [pixelass](https://github.com/pixelass)
* Url(s)    : [codepen](http://codepen.io/pixelass)
* previous talks: 
  * https://www.youtube.com/watch?v=fjcOe4sYErk
  * https://www.youtube.com/watch?v=hXTRISz5q_Q

## The story you'd like to tell

This talk is a guide on how to create amazing fractals with CSS. Fractals are a natural phenomenon mostly based on mathematical functions/algorithms. You will see how Gregor learned to create them with CSS and discovered the fractal world of CSS. After an intro and a live-coding session Gregor will connect the fractals he created to webAudio and visualise the frequency via a fractal.

## Speaker Bio

![gregor_adams_256 copy](https://cloud.githubusercontent.com/assets/1148334/6177584/33ab3982-b308-11e4-9f36-d36ba189cbac.png)

Gregor Adams is a self-taught web developer with a strong focus on CSS. He works as a front-end developer and architect at [SINNERSCHRADER](http://sinnerschrader.com).  
Gregor is very active on [codepen](http://codepen.io/pixelass/) where he shows a lot of abstract CSS experiments. While he has no special focus when is comes to CSS his most impressive works are related to 3d shapes or fractals.  
Gregor speaks at conferences and meetups with a strong urge to teach or help other developers. He pushes his own limits every day, staying up to date with the latest specs, finding fixes for browser quirks or trying to do the impossible.

**Comment by ericnkatz** [comment]
Just an aside, love what you've done with your codepen profile. :+1:

**Comment by pixelass** [comment]
@ericnkatz haha.. thx.   
You just put a smile on my face.
