### ISSUE TITLE
JavaScript Style Sheets: The CSS Alternative That Never Was

### ISSUE THREAD

**Issue by stevekinney** [cascadiajs/2015.cascadiajs.com#139]
# JavaScript StyleSheets: The Future That Never Was

* Name      : Steve Kinney
* Location  : Denver, Colorado
* Email     : hello@stevekinney.net
* Twitter   : [@stevekinney](http://twitter.com/stevekinney)
* GitHub    : [stevekinney](http://github.com/stevekinney)
* Url(s)    : [stevekinney.net](http://stevekinney.net)

## The story you'd like to tell

JavaScript Style Sheets (JSSS) were introduced by Netscape in 1996 as a competing specification to Cascading Style Sheets (CSS). Most recently, it was available in Netscape Communicator 4.0. The technology died in 2000, when Netscape removed it from Communicator 6.0.

JavaScript Style Sheets allowed you to define custom styling rules for your web pages. However, Cascading Style Sheets did have one thing that JavaScript Stylesheets were missing: like the whole idea of "cascading." JSSS did not let you define the style of am <code>em</code> within an <code>h1</code>. That said, JSSS allowed the developer to use the full weight of the language, including functions and conditionals to style the DOM.

JSSS tackled many of the same problems as CSS. It had a similar box model and handled inheritance the same way as CSS. In this talk, we’ll review the history of JSSS, examples of JSSS from the past, what it did better than CSS, what it did worse than CSS, what we can learn from JSSS, and—for the adventurous among us—using JSSS today. We'll even see some JSSS it in action.

We'll look at how some of the concepts present in JSSS—that didn't make it into CSS—re-emerged in technologies like React as well as Sass and LESS.

## Speaker Bio

![Steve Kinney](https://dl.dropboxusercontent.com/u/505445/stevekinney-256.png)

Steve teaches Ruby and JavaScript to aspiring web developers at the Turing School of Software and Design in Denver, Colorado. Prior to Turing, he was a New York City public school teacher where he taught programming to middle and high school students.

**Comment by misscs** [comment]
Interesting history lesson. Pretty intrigued by this talk as I don't know anything about JSS/ have never heard of it until now. 

Do you see any correlation to React and the current cries from some in the industry to let JS handle your styles?

**Comment by stevekinney** [comment]
JSSS is obviously not without its flaws (which is part of the reason we don't use it today.) But it's super interesting to see how some of the concepts present in JSSS—that didn't make it into CSS—re-emerged in technologies like React as well as SASS and LESS.

**Comment by misscs** [comment]
Rad! I was hoping there was a connection between JSSS concepts and
modern technologies. I think it would add value to your talk to include
something to the extent of

> We'll look at how some of the concepts present in JSSS—that didn't
> make it into CSS—re-emerged in technologies like React as well as Sass
> and LESS.

I'd be very interested in hearing this talk.

**Comment by stevekinney** [comment]
@misscs Consider it done. :wink:
