### ISSUE TITLE
Stop Breaking the Web

### ISSUE THREAD

**Issue by bevacqua** [cascadiajs/2015.cascadiajs.com#142]
# Stop Breaking the Web

* Name      : Nicolas Bevacqua
* Location  : Buenos Aires, Argentina
* Email     : nicolasbevacqua@gmail.com
* Twitter   : [@nzgb](https://twitter.com/nzgb)
* GitHub    : [@bevacqua](https://github.com/bevacqua)
* Url(s)    : [ponyfoo.com _(blog)_](http://ponyfoo.com)
* Url(s)    : [bevacqua.io _(JavaScript book)_](http://bevacqua.io/bf)

## The story you'd like to tell

We are breaking the web. Progressive enhancement is completely ignored by modern frameworks where we rely solely on client-side rendering. We must reinvent web framework architecture that take shared rendering seriously while not giving up on progressive enhancement. We must stop breaking the web for the sake of developer productivity. Instead, we should build applications with the humans in mind.

## Speaker Bio

[![bevacqua.png](https://avatars3.githubusercontent.com/u/934293?v=3&s=460)](https://github.com/bevacqua)

Nico is an enthusiastic JavaScript hacker, author, and public speaker based in Buenos Aires, Argentina. When he's not hacking away at freelance projects, or contributing to the open source community as [@bevacqua][1], Nico spends time writing content for [Pony Foo][2]  and devoting time to local communities such as [NodeSchool][6], as well as [Beer.js][7]; and he’s published a book, [**JavaScript Application Design**][3]. Nico is a happy pony, and you can find him as [@nzgb][4] on Twitter, because [xkcd][5].

[1]: https://github.com/bevacqua
[2]: http://ponyfoo.com/
[3]: http://bevacqua.io/bf
[4]: https://twitter.com/nzgb
[5]: http://xkcd.com
[6]: http://nodeschool.io/buenosaires/
[7]: https://github.com/beerjs/buenosaires

**Comment by DavidBruant** [comment]
I like your talk proposal :-) I hope it'll get accepted.

**Comment by bevacqua** [comment]
Thanks!
