### ISSUE TITLE
Build detailed timeline for organizing CJS Fest

### ISSUE THREAD

**Issue by hackygolucky** [cascadiajs/2015.cascadiajs.com#15]
Provide a detailed timeline that is living and breathing to keep organizers/curators/volunteers informed about actions to come.

**Comment by hackygolucky** [comment]
See this funtimes! https://github.com/cascadiajs/cascadia-staff#cascadiajsfest-2015

**Comment by davethegr8** [comment]
Awesome! Can we also get something in there about a design for the website, or are we just planning on using last year's design (with new photos from the venue)?

**Comment by hackygolucky** [comment]
No, that totally needs to be added.

 I was building a similar one for EmpireJS as well and we tend to just fork last year's with additions from a graphic designer.
