### ISSUE TITLE
Talk: Going All-Cloud with Browser-based IDEs

### ISSUE THREAD

**Issue by stuartpb** [cascadiajs/2015.cascadiajs.com#150]
# Going All-Cloud with Browser-based IDEs

* Name      : Stuart P. Bentley
* Location  : Cascadia, USA
* Email     : stuart@testtrack4.com
* Twitter   : [@stuartpb](https://twitter.com/stuartpb)
* GitHub    : [stuartpb](https://github.com/stuartpb)
* Url(s)    : [stuartpb.com](https://stuartpb.com)

## The story you'd like to tell

When I tell people the majority of my coding over the last two years has been within a web browser, they tend to be surprised and intrigued, with lots of questions. "Is that really viable?" "Isn't it slow?" "What does coding in your browser get you?"

In this talk, I do some development with my Chromebook, while addressing questions like these (especially the last one). I'll demonstrate testing and deployment with Cloud9 and Heroku, as well as local development for Chrome extensions using the Chrome Dev Editor. I'll also talk about the few areas where I need to go outside of ChromeOS for my needs, and how these can be addressed (crouton, legacy-bios booting off of a USB device).

## Speaker Bio

![](https://avatars2.githubusercontent.com/u/572196?v=3&s=460)

I'm a magical sloth that likes to crawl and climb through South Lake Union and sit in WeWork and I write code sometimes. I've been using Cloud9 almost exclusively for all my development work since December 2012. I have a mostly-green GitHub contribution graph, and a whole bunch of repos on GitHub (116 non-fork repos on my user account, plus many more kept under organizations like https://github.com/plushu).

Most of my workspaces on Cloud9 are public, so you can see my work in progress on any of my projects at https://c9.io/stuartpb

**Comment by stuartpb** [comment]
This'd be a redux of [the presentation I gave at SeattleJS in December](https://github.com/seattlejs/seattlejs/issues/23), the video for which unfortunately was lost due to technical difficulties.

One question I have: for the demo portion of this talk, is there an interesting API I can call out to related to CascadiaJS? (Something more interesting than just a hashtag?)

**Comment by davethegr8** [comment]
Did you have something in mind API wise?

**Comment by stuartpb** [comment]
Not really- unlike a framework-based demo, I don't have any specific technology I'm looking to showcase in the app, since this presentation is about *building* the app. Last time, I built an app that applied the http://xkcd.com/1288/ substitutions to any page (or, at least, *tried* to) - I think this time I might like to go for something a bit more event-specific, and maybe realtime. (I could probably just do something like the http://rethinkdb.com/blog/cats-of-instagram/ demo with a Cascadia hashtag, though.)
