### ISSUE TITLE
Create preliminary CFPs for individuals CJS Fest days

### ISSUE THREAD

**Issue by hackygolucky** [cascadiajs/2015.cascadiajs.com#16]
Modify and improve the CFP from prior years to specify for the change in concerns.

Individual days to target:
- CSS
- Node
- Browser

Changes to work in:
- flow changes to issue filing as opposed to PR submission
- Make sure to include information that a talk does not have to be shoehorned into a particular day and can be submitted for more than if the submission fits.
- timeline for submitters to expect feedback as well as final announcements for accepted/rejected talks

* Keep in mind that this is all to be provided to curators(finalized in January) for their own editing prior to the CFP announcement in January.

**Comment by KatieK2** [comment]
Closing this - CFP is done.
