### ISSUE TITLE
Twitter Assistant

### ISSUE THREAD

**Issue by DavidBruant** [cascadiajs/2015.cascadiajs.com#160]
# Twitter Assistant

* Name      : David Bruant
* Location  : Bordeaux, France
* Email     : bruant.d@gmail.com
* Twitter   : [@DavidBruant](https://twitter.com/DavidBruant)
* GitHub    : [DavidBruant](https://github.com/DavidBruant)

## The story you'd like to tell

**Twitter data** are used for a variety of purposes, most often for marketing purposes or one-shot visualization. However, they can also be useful for people who have nothing to sell, just to better understand how other people use Twitter in order to make better informed decisions on questions like **"should I follow this person?"**

**Twitter Assistant** is such a tool. It is an **open source browser addon** that adds information in-context while visiting Twitter web. Twitter Assistant differentiates itself from other service/product dealing with Twitter data in that it is **open source** (so the computed metrics aren't black magic) and the **addon discusses directly with the Twitter API** (no third-party server dependency).

This talk will describe the technical architecture of Twitter Assistant that resulted from the worthwhile constraint of making a useful and easy-to-use tool without unnecessary dependencies.
Among other things, this talk will cover: 
* a short **reminder of how addons work**
* how to **work around various OAuth limitations**
* **UX concerns** related to addons and the Twitter API
* **data mining meaningful metrics** out of Twitter data
* how moving to TypeScript pretty much fixed a bug I didn't need to chase down and made easier adding some features

At the time of writing this description, an early version of the addon is already [available on Firefox](https://addons.mozilla.org/fr/firefox/addon/twitter-assistant/)

## Speaker Bio

![](https://cloud.githubusercontent.com/assets/165829/6320121/39c34db6-bad6-11e4-9c57-ae0d1311055f.jpg)

David Bruant in a social entrepreneur dedicating his time and skills to projects he believes in.
He contributes to Mozilla and Open Web Standards. He teaches coding to kids and beginner adults.
He's recently been awarded three times with France public funds to work on open sources projects
* [6element](https://github.com/anthill/6element), a web applications helping citizens to find alternative to recycling centers for their waste (selling on second-hand market, donation, repairing, etc.)
* [Twitter Assistant](https://github.com/DavidBruant/Twitter-Assistant), the addon described in the talk

**Comment by oncletom** [comment]
> how to work around various limitations of the Twitter API

And how OAuth is not designed to be server-less, and can be an unnecessary need to scale a service (whereas in your case, if the API scales, your extension scales). 

> This talk will describe the technical architecture of Twitter Assistant that resulted from the worthwhile constraint of making a useful and easy-to-use tool without unnecessary dependencies.

It sounds uber-marketing to me :-D Is it worth directly stating incremental tooling and evocating your move to TypeScript and what it brought in term of development ease?

**Comment by DavidBruant** [comment]
> It sounds uber-marketing to me :-D

... yeah... I overdid it a bit :-p But in a way, that's the big thing I can talk about. It took me a year to come up with this architecture, I'd be happy to share it with the audience so people who'd want to do something benefit from my experience and save the time I wasted.

I'll mention TypeScript.

**Comment by oncletom** [comment]
> It took me a year to come up with this architecture, I'd be happy to share it with the audience so people who'd want to do something benefit from my experience and save the time I wasted.

*That* ;-)
