### ISSUE TITLE
6element - Open hardware, machine learning and a web app to reduce waste

### ISSUE THREAD

**Issue by DavidBruant** [cascadiajs/2015.cascadiajs.com#162]
# 6element - Open hardware, machine learning and a web app to reduce waste

* Name      : David Bruant
* Location  : Bordeaux, France
* Email     : david.bruant@ants.builders
* Twitter   : [@DavidBruant](https://twitter.com/DavidBruant)
* GitHub    : [DavidBruant](https://github.com/DavidBruant)

## The story you'd like to tell

When we ([Ants](http://ants.builders/)) met **local authorities responsible for waste disposal**, we met excellent and highly professional people, but people who were solely **focused on their core business**: collecting and processing waste. However, **citizens** we talked to told us they had **various frustrations** especially being rejected from recycling centers because the bin for their waste was full.

Understanding this issue, we started the **6element** project which is composed of various pieces, each of them is **open source**:
* An **open hardware sensor** to measure the level of all bins in real time (using SMS to send the protobuf-encoded data cheaply).
* A **Machine Learning algorithm** to make predictions on the level of bins
* A **service matching waste description with various alternatives to recycling centers** (second-hand re-sellers, charities, repairing)
* A **web application to inform the citizens in real time** of the state of recycling centers bins (to prevent the frustration of going there for no reason) and suggesting alternatives to recycling centers.

This talk will cover an architecture overview of the project and dive into the various parts and how they fit together with a particular focus on the web parts (matching service and web application for the citizens).

## Speaker Bio

![](https://cloud.githubusercontent.com/assets/165829/6320121/39c34db6-bad6-11e4-9c57-ae0d1311055f.jpg)

David Bruant in a social entrepreneur dedicating his time and skills to projects he believes in.
He contributes to Mozilla and Open Web Standards. He teaches coding to kids and beginner adults.
He's recently been awarded three times with France public funds to work on open sources projects
* [6element](https://github.com/anthill/6element), the project described in this talk
* [Twitter Assistant](https://github.com/DavidBruant/Twitter-Assistant), an open source browser addon improving the Twitter web experience.

**Comment by oncletom** [comment]
> we met excellent and highly professional people, but people who were focused on their core business

I would not say _but_ but _and_. It is _but_ for you; hopefully they are focused on their core business ;-)

It would be worth mentioning what you learnt from their business, that your ideal vision of the project did not not match with their agenda (cf. the dashboard) and this project has been successful because you spent enough time _before_ and _during_ the project, rather than just catching up with barely readable specs and coding in a basement.

**Comment by DavidBruant** [comment]
> > we met excellent and highly professional people, but people who were focused on their core business

> I would not say but but and. It is but for you; hopefully they are focused on their core business ;-)

But that's the reason why they fail to innovate and why they've "delegated" their innovation to us, though. I added a word to emphasis that part.

> It would be worth mentioning what you learnt from their business, that your ideal vision of the project did not not match with their agenda (cf. the dashboard) and this project has been successful because you spent enough time before and during the project, rather than just catching up with barely readable specs and coding in a basement.

Given CascadiaJS' focus on technology (hence CSS/BrowserJS/ServerJS split), I chose to not mention it in the description, but I'll say a word about it in the talk.

Thanks for the comments @oncletom :-)

**Comment by oncletom** [comment]
:+1:

**Comment by vallettea** [comment]
:+1

**Comment by oncletom** [comment]
:hand:
