### ISSUE TITLE
Multi-package Programming In JavaScript

### ISSUE THREAD

**Issue by rkamradt** [cascadiajs/2015.cascadiajs.com#168]
# Multi-package Programming In JavaScript

* Name      : Randal Kamradt
* Location  : Tacoma, WA
* Email     : randysr@kamradtfamily.net
* Twitter   : [@rkamradt](https://twitter.com/rkamradt)
* GitHub    : [rkamradt](https://github.com/rkamradt)
* Url(s)    : [OMG Another Blog](https://rlkamradt.wordpress.com)

## The story you'd like to tell

Building a framework that uses JSON data definition language to simplify and unify other aspects of application development. This presentation is less about the example framework I present than about building frameworks, and how to build in-the-large. The presentation will follow closely my [multi-part blog](https://rlkamradt.wordpress.com/category/meta-programming-in-javascript/). Topics include:

* Making a project NPM friendly.
* Splitting projects to increase reusability and decrease dependency pains.
* Documenting your project with JS docs, code coverage and usable samples.
* Publishing and versioning through NPM.
* Creating a project site on GitHub.

## Speaker Bio

![](http://www.gravatar.com/avatar/73b47b6be923d4b00479277db965f63e.png)

I have been a computer programmer since I found a C compiler for my Atari personal computer. I have transitioned from one technology to another over the years, and now find myself working with JavaScript and Node.js. I give presentations and do mentoring at the Tacoma-JS meetup. When I'm not programming I split my time between family, music, painting, and writing.

**Comment by GregBulmash** [comment]
Randy, can you provide some examples of a problem this solves or a pain
point this eases? You might want to include links to the specific blog
posts in the proposal.

**Comment by rkamradt** [comment]
Hi Greg! I didn’t know you were associated with the conference. Thanks for the feedback, I’ll adjust the write-up later today. I must say, I like the way this is organized on GitHub.

Randy
