### ISSUE TITLE
Breaking Free from Bootstrap

### ISSUE THREAD

**Issue by jdsteinbach** [cascadiajs/2015.cascadiajs.com#169]
# Breaking Free from Bootstrap

* Name      : James Steinbach
* Location  : Denver, CO
* Email     : jdsteinbach@gmail.com
* Twitter   : [@jdsteinbach](https://twitter.com/jdsteinbach)
* GitHub    : [jdsteinbach](https://github.com/jdsteinbach)
* Url(s)    : [jdsteinbachcom](https://jdsteinbach.com)

## The story you'd like to tell

Prefab CSS grid frameworks (like the ones included in Foundation, Bootstrap, et al) are opinionated and heavy. They force designers to honor unnecessary constraints, developers to follow arbitrary conventions, and users to wait on bloated page loads.

By switching to a Sass grid system like Susy, we can free designers to pursue custom grids, save ourselves hours of clean-up, and give our users light, fast pages. 

Outline:
* Concerns with heavy CSS grid frameworks
* Basics of Susy
* Advanced features of Susy

Slides available [here](https://www.slideshare.net/JamesSteinbach/breaking-free-from-bootstrap)

## Speaker Bio

![James Steinbach](http://jamessteinbach.com/img/james-bkgd-1500x1000.jpg)

I'm a front-end architect with a passion for Sass-organized modular code, meaningful animation, and content-centric semantic markup. When I'm not at work I'm probably spending time with my wife & baby daughter … or, occasionally still at a computer trying out some [fun front-end stuff](https://codepen.io/jdsteinbach).

**Comment by alexlande** [comment]
Hi @jdsteinbach, thanks for the proposal!

This talk sounds very cool, Susy is a great grid framework.

I don't know that I completely follow the way you've positioned Bootstrap/CSS frameworks and Susy/grid systems. You've included the line "Those frameworks are usually used primarily for one reason: pre-built grids.", but I think that's probably up for debate. Personally, I might steer a little more heavily in one of two directions:

- Outlining *other* alternatives to CSS frameworks (and/or reasons not to use them) outside of the grid system. Including discussion of modular CSS packages like SUIT CSS, or the benefits of rolling your own buttons, or typographic systems, or whatever, could make the argument that you don't need Bootstrap more compelling.
- Positioning the talk more directly as a discussion of why Susy is so awesome, better + more powerful than the limited grid systems provided by a more all-encompassing CSS framework.

**Comment by jdsteinbach** [comment]
Thanks for the feedback: I'd refine my talk description with the second option: prefab CSS grid systems are limiting and bloated; Susy (& its kin) are powerful, customizable, and lightweight. You can see the slides I'd use as a starting point [here](www.slideshare.net/JamesSteinbach/breaking-free-from-bootstrap) if that helps.

**Comment by alexlande** [comment]
Cool! Your focus is definitely more clear after looking through your slides. :+1:

**Comment by KatieK2** [comment]
Hi @jdsteinbach! Cool, thanks! I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - everyone is guaranteed to see.

**Comment by jdsteinbach** [comment]
Thanks, @KatieK2 - updated!
