### ISSUE TITLE
 6 ways to react to and control screen orientation changes in HTML5

### ISSUE THREAD

**Issue by jerle76** [cascadiajs/2015.cascadiajs.com#172]
# 6 ways to react to and control screen orientation changes in HTML5

* Name      : Jerome Lecomte
* Location  : Toronto, Canada
* Email     : jerle76@gmail.com
* Twitter   : [@jerle76](https://twitter.com/jerle76)
* GitHub    : [jerle76](https://github.com/jerle76)
* Website   : [jerle76.me](http://www.jerle76.me)

## The story you'd like to tell

Would you enjoy playing Super Mario World scaled down to fit Portrait mode or Ikaruga in Landscape mode on your smartphone?

![Super Mario World in Portrait](https://cloud.githubusercontent.com/assets/1383818/6377322/53ce3104-bcf1-11e4-89a2-440ade1faec9.jpg) ![Ikaruga in Landscape](https://cloud.githubusercontent.com/assets/1383818/6377305/480d161e-bcf1-11e4-8d01-1721a6d03e6d.jpg)

Probably not: you would naturally orient your device to match the game's layout, thus fully utilizing your screen size.

Similarly some web applications are most legible and easiest to interact with in a particular device orientation. For example, I find Landscape best suited for street maps and theater seat selection, whereas Portrait is ideal for calendars and news articles.

But how to enforce such orientations?

Building upon my experience making [Forex Hockey](http://www.jerle76.me/forex-hockey) (an HTML5 2-player tablet game), I will present the State of the Union of screen orientation on the web. Attendees will leave with an overview of 6 ways to react to and control screen orientation changes in web applications, covering:

- CSS media queries
- orientation events
- HTML5 APIs
- application manifests

## Speaker Bio

![Jerome Lecomte](https://cloud.githubusercontent.com/assets/1383818/6377336/730302e8-bcf1-11e4-8cf1-be288173d41e.jpg)

I am a software developer with more than a decade of experience in UI design and front-end technologies. I like building all sorts of web apps using HTML5 and Javascript. I've given a couple of talks at HTML5 meetup or [workshop](https://www.youtube.com/watch?v=6_PmFSSqbDU) in Toronto. When I'm not working or playing with LEGO, retro video games and wearable computing I can be found entertaining my 2 boys and twin girls.

**Comment by jden** [comment]
+1 I'd love to learn more about this
