### ISSUE TITLE
I See

### ISSUE THREAD

**Issue by anvaka** [cascadiajs/2015.cascadiajs.com#175]
# I see

* Name      : Andrei Kashcha
* Location  : Seattle, WA, USA
* Email     : anvaka@gmail.com
* Twitter   : [@anvaka](https://twitter.com/anvaka)
* GitHub    : [anvaka](https://github.com/anvaka)
* Url(s)    : [npm universe](http://anvaka.github.io/allnpmviz3d/), [github projects discovery](http://www.yasiv.com/github/#/), [amazon graph](http://www.yasiv.com/amazon)

## The story you'd like to tell
*Topics: WebGL, Parallel JavaScript, Software Design, Performance, Algorithms*

Have you seen npm? It's a beautiful universe of freedom, love and passion. Four months ago I've build [a spaceship](https://github.com/anvaka/allnpmviz3d#big-bang-of-npm) to fly through this universe. Now I want to invite cascadia's guests to fly with me further. We will visit neighboring galaxies of bower, cpan, and something else... (this is a secret yet :octocat:  !). Along the way I will share how to build fast, large scale data visualizations and keep code complexity under control.

## Speaker Bio

![i still need a better picture]
(https://en.gravatar.com/userimage/12709737/1c453766d53c89c821284ade1cd05ce6.jpg?size=256)

Hello, I'm a software developer from Ukraine, currently living and working in Seattle. I love programming, people and life.

**Comment by ryan-roemer** [comment]
Hi @anvaka -- I'm on the Server JS day talk review committee. `allnpmviz3d` looks really cool! Can you add to this abstract to give us more details about the techniques and technologies used in the project, and more discussion of what cool things your talk will cover?

**Comment by anvaka** [comment]
Hi Ryan,

I've added tags to the description. Do you think this is enough? Or more details is required?

**Comment by GregBulmash** [comment]
I just want to link to Andrei's presentation at SeattleJS, because it was
pretty awesome:
https://www.youtube.com/watch?v=GJTUsiXHcLw

**Comment by anvaka** [comment]
haha, thank you @GregBulmash !
