### ISSUE TITLE
We fail to follow SemVer – and why it needn’t matter

### ISSUE THREAD

**Issue by boennemann** [cascadiajs/2015.cascadiajs.com#180]
# We fail to follow SemVer – and why it needn’t matter

* Name			: Stephan Bönnemann
* Location	: Munich, Germany
* Email			: stephan@boennemann.me
* twitter		: [@boennemann](https://twitter.com/boennemann)
* github		: [boennemann](https://github.com/boennemann)
* Url(s)		: 
	- [semantic-release](https://github.com/boennemann/semantic-release)
	- [grunt-semantic-release](https://github.com/boennemann/grunt-semantic-release)
	- [http://hood.ie/blog/semantic-releases.html](http://hood.ie/blog/semantic-releases.html)

## The story you'd like to tell

If extensive libraries and even the tiniest module followed SemVer strictly, dependency hell would be a thing of the past … but humans weren’t made to follow rules.

There are over 125.000 packages on npm today. By the time of this conference, at least another 15.000 will have been added. Using the right packages in your own modules and applications makes JavaScript the joy to develop it is today. But if even immensely popular libraries fail to properly declare breaking changes, how can we trust the over 50.000 strangers who developed all these modules?
Currently we can’t. Let me show you how to write confidence-inspiring modules with breaking change detection and fully automated, tested releases including changelogs. Machines do a way better job with this than _buggy_ humans.

## Speaker Bio

![avatar image](https://secure.gravatar.com/avatar/29e45e7e0bf9561770aae5818f139c80.jpg?default=retro&filetype=jpg&rating=G&secure=true&size=256)

Stephan Bönnemann is a mad scientist in training. Making his way through HTML and CSS back in the early days he is now a JavaScript developer, with a strong passion for [automation](https://github.com/boennemann/semantic-release), [tiny](https://github.com/boennemann/url-safe) [modules](https://github.com/boennemann/animals) and [tools](http://hood.ie/)/[events](https://conc.at/) that make development accessible for more people.

**Comment by ryan-roemer** [comment]
@boennemann -- I'm on the Server JS day talk review committee. Can you add more details / takeaways / etc. to the abstract with regard to `"writ[ing] confidence-inspiring modules by leaving package publishing up to the machines"`? Thanks!

**Comment by boennemann** [comment]
Hey @ryan-roemer,

thanks for giving me opportunity to clarify that. I've added concrete takeaways now.

Best,
Stephan
