### ISSUE TITLE
Creating real time sheet music in the browser

### ISSUE THREAD

**Issue by fuhton** [cascadiajs/2015.cascadiajs.com#189]
# Creating real time sheet music in the browser

* Name      : Nick Smith
* Location  : Philadelphia, USA
* Email     : fuhton@gmail.com
* Twitter   : [@fuhton](https://twitter.com/fuhton)
* GitHub    : [fuhton](https://github.com/fuhton)
* Url(s)    : [fuhton.com](http://fuhton.com/)

## The story you'd like to tell

My mom wanted to hear and see the music I was creating and playing, and after consistent prodding, I slowly consented. You know how moms are. Taking advantage of the Web MIDI API and the VexFlow library I created an application to display real time sheet music. Using a light local BackboneJS environment to send MIDI information to a remote DB and creating a MIDI interpreter with a real time application around the VexFlow library, anyone can view the sheet music we are creating in real time around in the world. This library removes the need for music engraving software and increases access to new music.

## Speaker Bio

![](http://10up.com/wp-content/uploads/2014/09/nick-smith-sq-300x300.jpg)

Nick started as a Music Composition student blogging on the internet. Now he's a Web Engineer with 10up with an emphasis on UX development for web publishing. He works remotely from Philadelphia where he is involved in multiple Meetup groups.

**Comment by davethegr8** [comment]
... and now I want to get this and @geelen's `x-gif` together
