### ISSUE TITLE
Summarize attendee survey results from 2014

### ISSUE THREAD

**Issue by hackygolucky** [cascadiajs/2015.cascadiajs.com#19]
As requested(and a great idea) by @davethegr8, I'm going to revisit the attendee survey results for 2014 and summarize the findings to provide for (not yet named)organizers.

**Comment by jden** [comment]
Is this something you'd like help with? Are there any key insights or things to make sure to repeat or avoid based on participant feedback? Is this issue something we can move past? (it has a big scary "due in the past" label on it)

**Comment by hackygolucky** [comment]
I've just been under the weather and prioritized some other Cascadia stuff
first. @jden if you'd like to provide some postmortem on top of what I'll
be interpreting from the surveys(or you'd like to help with that
interpretation), you have access still
https://docs.google.com/spreadsheets/d/12aRPbCmzFFrs-5EkCZPu0V0xBWcADns8ysGH4w5dDJA/edit#gid=1340244563

**Comment by KatieK2** [comment]
Probably the boat has passed on this. OK to close this issue?
