### ISSUE TITLE
How to Argue About Programming

### ISSUE THREAD

**Issue by jasonrhodes** [cascadiajs/2015.cascadiajs.com#193]
# How to Argue About Programming

* Name : Jason Rhodes
* Location : Baltimore, MD
* Email : jason.matthew.rhodes@gmail.com
* Twitter : [@rhodesjason](http://twitter.com/rhodesjason)
* GitHub : [jasonrhodes](https://github.com/jasonrhodes)
* Url(s) : [rhodesjason.com](http://rhodesjason.com)

## The story you'd like to tell

If you haven't noticed, sometimes people argue about things in our community. Instead of shouting at everyone to stop, maybe we should focus on "harm reduction", or the idea that sometimes it's better to allow things to happen if they're clearly better than the alternative. Arguing about languages, philosophies, syntax, dress colors, strategies, tools, or important things isn't going anywhere. How can an argumentative community survive? How can it *not* alienate newcomers? How do you convince your coworkers when they're oh so clearly wrong? We should talk as a community about how to argue _better_.

In that spirit, I'd like to examine some of our most common community arguments, from frameworks to foundations, and suggest some ways of engaging each other that are more productive and respectful than the average screaming match. Having been involved in more than my share of this kind of thing, I'll share some stories and experiences about how ridiculous we all are sometimes.

Update: Mar 13th, [this great post](https://www.kateheddleston.com/blog/argument-cultures-and-unregulated-aggression) just came out today. I'll be incorporating some of its awesomeness into this talk, too.

## Speaker Bio

![Jason Rhodes profile](http://rhodesjason.com/assets/images/rhodesjason-01.square.256.png)

Jason used to play with HyperCard a lot during middle school classes and now he writes java scripts during basically all the different times. He lives in Baltimore, works on [SparkPost.com](http://sparkpost.com), organizes and leads [Baltimore NodeSchool](http://nodeschool.io/baltimore), creates dumb little GIFs at [meatspac.es](http://meatspac.es), and makes educational video series for [tutsplus](http://tutsplus.com/authors/jason-rhodes).

**Comment by GregBulmash** [comment]
Hi Jason,

I'm Greg. I'm one of the selection committee helpers and we've been asked
to help submitters clarify their pitches prior to the close of the CFP. One
question for clarification on my part:

"look for ways of engaging each other that are more productive and
respectful than the average screaming match."

Are you going to share some solutions you've discovered or engage the
audience to suggest them?

Thanks,

Greg

**Comment by jasonrhodes** [comment]
Hey Greg, I'll definitely be sharing these suggestions, not soliciting them. I'll update the wording for clarification. Thanks!

**Comment by lrlna** [comment]
I LIKE it! 

This got me thinking on a tangent - someone should talk about persuasion in programming. As in convincing your coworkers/OS contributors/teammates to go with your idea. Super important, and I would  be really into getting tips on that!

**Comment by jefflembeck** [comment]
Agreed with @lrlna - A "How to Win Friends and Influence People" for the modern workplace-style addition would be super awesome.

**Comment by lrlna** [comment]
no pressure, @jasonrhodes !! ;)

**Comment by jasonrhodes** [comment]
I would definitely hit on that as part of this talk, I think, but I don't think I have enough of that kind of material to submit it separately. I'll update to mention briefly. Thanks @lrlna @jefflembeck
