### ISSUE TITLE
Ideas for CascadiaJS  15

### ISSUE THREAD

**Issue by mstopham** [cascadiajs/2015.cascadiajs.com#2]
- app with all the event details
-CJS sunglasses, if summer conference (great for pics, just like umbrellas for '13)
-photo booth set up...just backdrop of the flag? Or an actual photo backdrop w/ the cascadia logo everywhere, tripod, camera person...(We got some great team photos taken when we went to CTA conf.)Then we can use these later to tweet to the different team for continual engagement
-station(s) set up to power up your devices (helpful)
-gift cards for ppl being awesome at the conference -- attendees, speakers, volunteers...nothing big -- $5 for a coffee/ice cream
-maybe a dif conference badge this year -- one that has the schedule on one of the sides, if no app
-hidden secret cards/stickers/tats...with clues to a mystery. People send answers to twitter w/ hash #cjs15

**Comment by Frijol** [comment]
Following up on this discussion– any interest from the community in having a hands-on event for attendees? I'd be up for running a Nodebots thing.

**Comment by bryan-m-hughes** [comment]
I'm always up for a NodeBots hack!

SumoBot hacks seem to always go over well because they're pretty accessible for beginners, are cheap (especially with PawelBots, cc @makenai), and there is a friendly competition at the end of the event that helps create a tighter community feel.

**Comment by KatieK2** [comment]
I participated in a Sumbots thing last year, it was great! (Though we can do it without soldering.) I offered to run this for CJS somewhere else, but now I am too busy to lead. :( It would still be lovely if it happens! So yes, thanks to all who are interested!

**Comment by TheAlphaNerd** [comment]
I would love to help out with some sort of node bots project as well!

**Comment by bryan-m-hughes** [comment]
Yeah, solder-free bots is definitely the way to go, and PawelBots don't require soldering. @Frijol do you know if a tessel+servo module will fit in the PawelPot chassis? wireless PawelBots would be awesome :)

I'd be more than happy to help @Frijol organize this too along with @TheAlphaNerd.

**Comment by hackygolucky** [comment]
We don't currently have room for any workshops in the schedule, but stay
tuned please! The organizers and curators need to powwow!

**Comment by makenai** [comment]
Cool - thanks for the cc! I'm happy to help out any way we can. Solderless is definitely possible - I've been using some mini shields created by Frank from Coder Dojo DC to simplify the process: https://oshpark.com/shared_projects/TEsKZkdg

Wireless is possible too. Currently they work great with Spark Cores and thus should be fine with the new $20 photon as well for an affordable option. I haven't tried with a tessel, but can't forsee any problems. Happy to provide kits or content or advice if you'd like!

**Comment by Frijol** [comment]
Tessel unfortunately doesn't fit nicely onto @makenai 's wonderful bots. @makenai , is the CAD parametric? I've been meaning to modify yours into a version that fits Tessel nicely. Or better yet, I want to make a version that has an open box on top so you can just put whatever you want in there (battery, sensors, etc.) – like [this](https://projects.tessel.io/projects/tesselbot-rc-sumobot) but less terrible.

(tangential but adorable Vine so you can see how broken my particular bot is: https://vine.co/v/ObTV02AZYh5)

**Comment by makenai** [comment]
LOL'd at the video. Love it.

The design is parametric - I don't have any up to date documentation, but I use this OpenSCAD file to generate both the 3D print and laser files currently: https://github.com/makenai/sumobot-jr/blob/master/3d_print/sumobot.scad

I've been meaning to pick myself up a tessel, so maybe I'll take this excuse to see how to get it to fit nicely. :)

**Comment by KatieK2** [comment]
🐳 ("WHALP") Welp! We've got our workshops more ore less slotted in now, so I'm closing this issue. Yay for all the great info!
