### ISSUE TITLE
Creatively Building A Cloud

### ISSUE THREAD

**Issue by kstewart** [cascadiajs/2015.cascadiajs.com#200]
# Creatively Building A Cloud

* Name      : Kevin Stewart
* Location  : Snohomish, WA USA
* Email     : kevin@kstewart.me
* Twitter   : [@kstewart](https://twitter.com/kstewart)
* GitHub    : [kstewart](https://github.com/kstewart)
* Url(s)    : [re:engineering management](http://kstewart.me/)
                 [Creative Cloud Assets](https://assets.adobe.com/)

## The story you'd like to tell

Adobe Creative Cloud offers all of the company's creative tools and services for desktop, mobile and the Web under a simple subscription offering. In this talk, we will look at how JavaScript and Node are being used in some of these services including the first service built, Adobe Creative Cloud Assets. Much of the story will be about how Adobe Creative Cloud Assets was built and the real-world situations that caused us to evolve our technology stack from Ruby to Node.js to a mix of Node.js and Go. 

## Speaker Bio

![](https://pbs.twimg.com/profile_images/411994393231372288/fiPif7_Q.jpeg)

I lead engineering for Creative Cloud Assets (https://creative.adobe.com/products/assets) which lets you store, iterate, collaborate and reuse your files and creative assets to keep you connected to your creativity at the office, at home or on the go with convenient access from your desktop and mobile device. My team designed and built the Web application (https://assets.adobe.com) using HTML5, CSS and Javascript, including a content-aware plugin model to enable increased interactivity and editing as is found in Creative Cloud Extract (http://www.adobe.com/creativecloud/extract.html). We also implemented the Web experience and collaboration features for Creative Cloud Libraries (http://www.adobe.com/creativecloud/libraries.html).

**Comment by ryan-roemer** [comment]
Hi @kstewart ! 

I'm on the Server JS day talk review committee. Can you perhaps add some details as to what types of things / technologies you are using with JavaScript to help build your cloud service? E.g., so as a potential attended, I can point to something and say "I'd like to learn about building cloud services with JS using THAT / doing THIS!"

**Comment by kstewart** [comment]
@ryan-roemer 

# Frontend

* Backbone
* underscore
* Plain ol' JavaScript

# Backend

* Node.js
* Restify
* AWS SDK
* node-redis

**Comment by kstewart** [comment]
We actually use many more Node modules, but that would be too granular for the talk
