### ISSUE TITLE
How to talk to humans: a different approach to soft skills

### ISSUE THREAD

**Issue by sharonsteed** [cascadiajs/2015.cascadiajs.com#202]
Name: Sharon Steed
Location: Pittsburgh, PA, USA
Email: sharon@speechirl.com
Twitter: @sharonsteed
GitHub: none
Url(s): work - speechirl.com personal - sharonsteed.co

The story you'd like to tell

Developers are trained to communicate to things with a goal in mind. When you're talking to something like, say a computer, you type in your code and it responds by giving you back what you want. Nine times out of ten, it works perfectly. Why, then, is it so difficult to do this same thing when talking to a client about a project, updating a superior on your progress, or pitching an investor your million-dollar idea? Because talking to people requires a special set of skills - namely, empathy and a little bit of storytelling. In an industry filled with brilliant minds, great ideas and mass disruption, so few of the best and brightest know how to tell their compelling story. The takeaways from this talk will be learning how to value the listener, improved social connection and becoming a master at building a relationship quickly and effectively.

Speaker Bio

avatar: https://media.licdn.com/mpr/mpr/shrink_500_500/p/6/005/056/29b/1b43068.jpg

Sharon is the director of business development and marketing for speech IRL, a Chicago-based communications firm specializing in therapy and training. She is a life-long stutterer that speaks about fear and vulnerability at the intersection of marketing, communication, business and tech. She has spoken to universities about stuttering, at Ignite Chicago about patience, Madison+ Ruby about vulnerability and to a host of other audiences. She lives in Pittsburgh.

**Comment by blakmatrix** [comment]
:+1:
