### ISSUE TITLE
State of the Animation

### ISSUE THREAD

**Issue by rachelnabors** [cascadiajs/2015.cascadiajs.com#203]
# State of the Animation

* Name      : Rachel Nabors
* Location  : Portland, OR, USA
* Email     : rachelnabors@gmail.com
* Twitter   : [@rachelnabors](https://twitter.com/rachelnabors)
* GitHub    : [rachelnabors](https://github.com/rachelnabors/)
* Url(s)    : [rachelnabors.com](http://rachelnabors.com)

## The story you'd like to tell

The post-Flash era is hardly free of animation. CSS animation is quickly becoming a cornerstone of user-friendly UI frameworks, and JavaScript libraries already exist to handle complex, interactive animations. And now there’s a new API coming to town specifically for web animations! In the wake of so much “CSS vs. JavaScript animation” infighting, you'll be introduced to the Web Animations API via the development styles and insights of four distinct groups of people: UI designers, interaction developers, library authors, and the browser teams implementing it.

This talk was also given at Fronteers and Webvisions NYC at the end of last year, SFHTML in a few weeks. It will be updated and tweaked, but not overhauled.

## Speaker Bio

![https://www.dropbox.com/s/rhp0sqr2s6le55v/256-cartoon.png?dl=0]
![https://www.dropbox.com/s/orgxqb9ftrn83lc/256-star.jpg?dl=0]

Rachel Nabors is an interaction developer and award-winning cartoonist. She travels the world, speaking about web animation and giving workshops. Her articles on the topic have been published in Smashing Mag, A List Apart, 24 Ways, and Net Mag. When not biking around her home city of Portland, Oregon in the USA, she makes interactive comics at her company [Tin Magpie](http://tinmagpie.com) and publishes [Web Animation Weekly](http://webanimationweekly.com). You can catch her as [@rachelnabors](https://twitter.com/rachelnabors) on Twitter and at [rachelnabors.com](http://rachelnabors.com).

**Comment by rachelnabors** [comment]
Keep in mind that there is no more CSS in this than there is JS. In fact, there's a lot about JS animation libraries in here.

**Comment by alexlande** [comment]
Ah, yes. Thanks :)

**Comment by misscs** [comment]
Will this talk differ or expand upon the version you gave at [Fronteers](https://vimeo.com/109912258)?

**Comment by rachelnabors** [comment]
Same talk, small updates :)


  [image: photo]
*Rachel Nabors*
Storycoder, speaker, founder, Tin Magpie
 w:rachelnabors.com
 <http://twitter.com/rachelnabors>  <http://dribbble.com/rachelthegreat>
<http://plus.google.com/u/0/+RachelNabors>
<http://linkedin.com/in/rachelnabors>
  ------------------------------
*Speaking & Workshops in 2015*

   - March 2015 Tag IT, Norway
   <http://tag-it.no/en/session/the-state-of-animation-2015-2/>
   - March 2015 SFHTML, San Francisco
   <http://www.meetup.com/sfhtml5/events/219966671/>
   - May 2015 Beyond Tellerand, Düsseldorf
   <http://lanyrd.com/2015/btconfdus/> & workshop
   <http://lanyrd.com/2015/btconfdus/sdhqmw/>

 <https://twitter.com/rachelnabors>
Latest Tweet: <https://twitter.com/rachelnabors> @helenvholmes
<https://twitter.com/helenvholmes> @_lilchen <https://twitter.com/_lilchen>
I thought we were talking about next year's SXSW. You could always come to
@xoxo! <https://twitter.com/xoxo!>
 17:47 Mar-10 <https://twitter.com/rachelnabors/statuses/575352295782641664>
Follow
@rachelnabors <https://twitter.com/intent/user?screen_name=rachelnabors>
<https://twitter.com/?status=@rachelnabors&in_reply_to_status_id=575352295782641664>
<https://twitter.com/?status=RT @rachelnabors @helenvholmes @_lilchen I
thought we were talking about next year's SXSW. You could always come to
@xoxo!>
   Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by KatieK2** [comment]
Hi @rachelnabors! Thanks for this proposal. Could you please update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thanks!

**Comment by rachelnabors** [comment]
Sure :)
