### ISSUE TITLE
The Trials and Tribulations of Engineering Social Software

### ISSUE THREAD

**Issue by TheAlphaNerd** [cascadiajs/2015.cascadiajs.com#205]
# The Trials and Tribulations of Engineering Social Software

* Name      : Myles Borins
* Location  : San Francisco, USA
* Email     : Myles [AT] famo.us
* Twitter   : [@thealphanerd](http://twitter.com/thealphanerd)
* GitHub    : [thealphanerd](http://github.com/thealphanerd)
* Url(s)    : [thealphanerd.io](thealphanerd.io)

## The story you'd like to tell

Creating software is tough. Creating software that is going to be used by developers in Production is reallllly tough.  In the last year I have had the chance to learn the hard way how tough it can be to engineer software that is used by developers.  Some examples include

* properly supporting software you didn't write and possibly don't understand
* dealing with haters (they gonna h8)
* deprecating api's gracefully
* supporting ALL THE TOOLS people use
* making decisions based on what people use, not what is technically the most accurate
* getting people to collaborate
* learning when to not immediately open source parts of a project

This talk can definitely be massaged in a number of ways. I am most interested in sharing the experiences I have had at Famo.us, a platform that has received both praises and hate.  Many of the lessons and experiences from working on smaller personal projects do not necessarily apply when you are supporting a community of developers, I think it is very worthwhile to share and explore the topic.

## Speaker Bio

![OMG ITSA ME](https://i.imgur.com/fEVQhKj.jpg)

Myles Borins is a developer, musician, artist, and inventor. He recently graduated with a Master of Music Science and Technology from c.c.r.m.a.  (a.k.a the center for computer research in music and acoustics).
He is currently working as Head of Open Source and Developer relations at Famo.us. In his spare time he helps to organize NodeBotsSF and Dance.js.

**Comment by nvcexploder** [comment]
This sounds good! Will the talk directly compare situations/problems from smaller, more personal libraries and bigger projects?

**Comment by TheAlphaNerd** [comment]
Indeed! A great example in particular is learning when not to immediately open source.  While on a small project there may not be many risks, you can potentially cause problems with a large community if you are ripping api's out from under them every week for a couple months.

**Comment by blakmatrix** [comment]
:+1:
