### ISSUE TITLE
It's not me it's you: on the fallibility of large systems

### ISSUE THREAD

**Issue by TheAlphaNerd** [cascadiajs/2015.cascadiajs.com#207]
# It's not me it's you: on the fallibility of large systems

* Name      : Myles Borins
* Location  : San Francisco, USA
* Email     : Myles [AT] famo.us
* Twitter   : [@thealphanerd](http://twitter.com/thealphanerd)
* GitHub    : [thealphanerd](http://github.com/thealphanerd)
* Url(s)    : [thealphanerd.io](thealphanerd.io)

## The story you'd like to tell

It's 2 a.m and you are staring into the abyss that is your computer screen. The letters are starting to blur, but you know what you've written.  This is the third time you have tried to implement the same thing from scratch today. Despite the fact that you have follow the api docs and industry best practices you just cannot seem to get anything to work!  Perhaps you should just give up this entire programming thing, you are obviously no good at it... :cry: 

NO

STOP THAT RIGHT NOW

It is very likely that the code you have written is perfectly fine, and that the problem exists somewhere lower in the stack.  This talk will introduce the concept of thinking about your code as a small part of a larger system.  It will also help show individuals how to peer into the abyss and find where the problem really exists.  The talk will be focused around a series of anecdotal examples of perfectly written code that just won't work.  From 3D matrix tranforms on SVGs in Firefox 34 to file watching in watchify, we will take a journey across the entire stack to see why the best thing to have as a developer is patience.

## Speaker Bio

![OMG ITSA ME](https://i.imgur.com/fEVQhKj.jpg)

Myles Borins is a developer, musician, artist, and inventor. He recently graduated with a Master of Music Science and Technology from c.c.r.m.a.  (a.k.a the center for computer research in music and acoustics).
Currently he is working as Head of Open Source and Developer relations at Famo.us. In his spare time he helps to organize NodeBotsSF and Dance.js.

**Comment by nvcexploder** [comment]
How far down that stack are you going to go?

**Comment by TheAlphaNerd** [comment]
All the way to libuv :smile:

**Comment by nvcexploder** [comment]
Rad!

**Comment by TheAlphaNerd** [comment]
Also the firefox rendering engine :smile:
