### ISSUE TITLE
Talk proposal: Professional ethics

### ISSUE THREAD

**Issue by thomblake** [cascadiajs/2015.cascadiajs.com#215]
# Professional Ethics for Software Engineers

* Name      : Thom Blake
* Location  : Oakland, CA
* Email     : thethomblake@gmail.com
* Twitter   : [@thomblake](https://twitter.com/thomblake)
* GitHub    : [thomblake](https://github.com/thomblake)
* Url(s)    : [thomblake.me](http://thomblake.me/)

## The story you'd like to tell

When we started calling ourselves "software engineers", it was an aspirational goal. We realized that a poorly-made computer program could pose as much danger to the public as a poorly-made bridge, so it was time to start taking ourselves seriously. Professional ethics is at the core of this outlook. It provides a series of guidelines so that we know what it is to be good at what we do.

A course on professional ethics is required for accrediation in software engineering, but most software engineers come from other backgrounds. Thus, it is up to each of us to learn about professional ethics and how it applies to what we do. This will be an overview of professional ethics for software engineers, including:

 * What is a profession?
 * What is professional ethics?
 * Why does professional ethics matter?
 * How can I apply professional ethics in my daily life?
 * Where can I go for more help with ethical issues?

## Speaker Bio

![](http://www.gravatar.com/avatar/f2e95fd17a0ad53f208d7ce61dd524f1.png)*avatar is required*

Thom Blake is a software engineer at BrightRoll, now part of Yahoo.  Thom studied Computer Ethics at SCSU, home of the Research Center on Computing and Society, and at De Montfort University, home of the Centre for Computing and Social Responsibility. Thom belongs to Oakland, the World Capital of JavaScript.

**Comment by blakmatrix** [comment]
:+1:

**Comment by misscs** [comment]
:+1: I'm definitely intrigued. 

In you opinion, what are some current examples of how software engineers are violating the code of professional ethics?

**Comment by thomblake** [comment]
I don't usually think about it in those terms, but I'll see if I can think up some examples if people find that sort of thing interesting.

On the positive side of the question, it seems that a lot of the "user first" thinking that gave rise to contemporary UX came out of the same early focus on professional ethics that brought about the "software engineer" label.

**Comment by misscs** [comment]
> On the positive side of the question, it seems that a lot of the "user
> first" thinking that gave rise to contemporary UX came out of the same
> early focus on professional ethics that brought about the "software
> engineer" label.



Fascinating. I would love to see you build on this hypothesis in the
talk, if you weren't planning on already.
