### ISSUE TITLE
Being good engineers did not prevent our startup to fail

### ISSUE THREAD

**Issue by oncletom** [cascadiajs/2015.cascadiajs.com#224]
# Being good engineers did not prevent our startup to fail

* Name      : Thomas Parisot
* Location  : London, United Kingdom
* Email     : thomas.parisot@bbc.co.uk
* Twitter   : [@oncletom](https://twitter.com/oncletom)
* GitHub    : [oncletom](https://github.com/oncletom)
* Url(s)    : [oncletom.io](https://oncletom.io)

## The story you'd like to tell

One day, I became the cofounder and CTO of a startup.
Six months after, the cash was missing and we never got paid again by the startup.
Thirty months after it melted down, the court finally closed the holding company.

Despite using Node.js in production early 2012 and had a solid engineering team, we were not cool enough to prevent the business failure.

I would like to skim through our learnings, victories and defeats as a free falling team.
I would like to demonstrate that focusing exclusively on your job is a mere illusion.
I would like to recall our emotional state, the jurisdictional battle and the reality of a business joint. 

I wish I would have known everything I will say before having started this adventure.

## Speaker Bio

![](https://raw.githubusercontent.com/oncletom/talks/master/thomas-parisot.jpg)

**Thomas Parisot is a Senior Web Engineer at BBC R&D** in London, United Kingdom. His work there involves compelling user experience prototypes, audio visualisation and Open Source collaboration thanks to JavaScript and Web technologies.

He is a believer of cross-disciplines learning, simple things and chance. Of course he likes cheese. Of course he likes wine. And [words](https://oncletom.io). And [pictures](https://oncletom.io/photos/).

Aside that, he co-created the [Sud Web conference](http://sudweb.fr) in France, has an upcoming Node.js book to be published in French and has no problem to admit he co-founded a startup which failed.

**Comment by DavidBruant** [comment]
> CTO of a French startup

It doesn't matter is French or otherwise.

> Despite we used Node.js in production 

Despite *using* Node.js

> we were not cool enough to prevent the business failure.

Just to be sure, did you mean to use "cool"? or is it a typo?

Other than that, yes. It's clear, concise, to the point. 
You may want to emphasis a bit more that we were an excellent engineering team, that the product was going fine and that concerns came from elsewhere.
