### ISSUE TITLE
Stronger Than Fear: Mental Health in the Developer Community

### ISSUE THREAD

**Issue by funkatron** [cascadiajs/2015.cascadiajs.com#228]
# Stronger Than Fear: Mental Health in the Developer Community

* Name      : Edward Finkler
* Location  : West Lafayette, Indiana, USA
* Email     : coj@funkatron.com
* Twitter   : [@funkatron](http://twitter.com/funkatron)
* GitHub    : [funkatron](http://github.com/funkatron)
* Url(s)    : [funkatron.com](http://funkatron.com)

## The story you'd like to tell

Mental disorders are the largest contributor to disease burden in North America, but the developer community and those who employ us are afraid to face the problem head-on. In this talk, we'll examine the state of mental health awareness in the developer workplace, why most developers feel it isn't safe to talk about mental health, and what we can do to change the culture and save lives. Attendees will leave with 5 things they can do to make their workplace safer for those dealing with mental health disorders.

This will essentially be an expansion of my [Open Sourcing Mental Illness](http://funkatron.com/osmi) talk, with content specifically focused on the state of mental health awareness and openness in the developer community. It will include detailed examination of data and anecdotes from the Mental Health in Tech survey I conducted in September 2014. The focus is on the impact of mental disorders on productivity, how we are failing to support those with mental health issues, and what we can do to change the status quo.

You can view the first version of this talk from PyTennessee 2015 at http://j.mp/stfpytn15video. New content would be present by July, though.

## Speaker Bio

![Sup](http://funkatron.com/content/ed_finkler_256x256.png)

Ed Finkler, also known as [Funkatron][1], started making web sites before browsers had frames. He does front-end and server-side work in Python, PHP, and JavaScript.

He served as web lead and security researcher at [The Center for Education and Research in Information Assurance and Security (CERIAS) at Purdue University][2] for 9 years, and he's an partner emeritus of [Fictive Kin][3]. Along with Chris Hartjes, Ed is co-host of the [Development Hell podcast][4].

Ed's current passion is raising mental health awareness in the tech community with his [Open Sourcing Mental Illness][5] speaking campaign.

Ed writes at [funkatron.com](http://funkatron.com).

 [1]: https://twitter.com/funkatron
 [2]: http://www.cerias.purdue.edu
 [3]: http://fictivekin.com
 [4]: http://devhell.info
 [5]: http://funkatron.com/osmi

**Comment by jakerella** [comment]
I don't know if the reviewers actually take community input on proposals, but I +1,000 this one. I've met Ed, and heard his "Open Sourcing Mental Illness" talk and not only do I think he is a knowledgeable and effective speaker, the topic is very important, and one few people are talking about.

**Comment by benedmunds** [comment]
+1
