### ISSUE TITLE
css via npm

### ISSUE THREAD

**Issue by sethvincent** [cascadiajs/2015.cascadiajs.com#229]
# css via npm

* Name: Seth Vincent
* Location: Seattle, WA
* Email: sethvincent@gmail.com
* Twitter: [@sethdvincent](http://twitter.com/sethdvincent)
* GitHub: [sethvincent](http://github.com/sethvincent)
* Url(s): [sethvincent.com](http://sethvincent.com)

## The story you'd like to tell

npm is great for server-side JavaScript, and with tools like Browserify npm works great for browser-side JavaScript, too. If we use npm for all our JS, it's frustrating to need another package manager just for CSS.

It turns out there's already CSS on npm, and we can use it with a variety of tools that offer a simple workflow that's very similar to using Browserify: 

- `npm install cool-css-package`
- `@import "cool-css-package";` in main CSS file.
- `npm run bundle-css`

Goals of the session: exploring what CSS and related tools exist now on npm, covering some best practices for publishing CSS packages, covering how pre-processors can be used with CSS published on npm, and discussing what issues still exist with the state of CSS on npm.

## Speaker Bio

![](https://avatars2.githubusercontent.com/u/164214?v=3&s=250)

Seth Vincent is a programmer, designer, and writer focused on journalism and civic technology projects. Currently he's building an open source, grant-funded project for managing data called [Flatsheet](http://github.com/flatsheet). Previously he’s worked as an advisor of a student news organization, advising on technology, journalism, and leadership. He is a co-organizer of [Code for Seattle](http://codeforseattle.org), a volunteer organization that uses technology to support civic engagement and address local issues.

**Comment by TheAlphaNerd** [comment]
This seems really interesting. Can you mention what tools you have been using. Specifically interested in what ```npm run bundle-css``` is doing under the hood :smile:

**Comment by sethvincent** [comment]
I often use [rework-npm](https://github.com/reworkcss/rework-npm) to bundle css, and made this command-line tool for it: [rework-npm-cli](https://github.com/sethvincent/rework-npm-cli), so the `npm run bundle-css` script looks something like this: `rework-npm source.css -o bundle.css`.

I'm putting together a full list now, but I've seen at least about a half-dozen tools related to bundling/requiring css from npm, some of which use rework-npm internally.

**Comment by misscs** [comment]
Will you be focusing on other tools that are not just rework or are the majority based on rework? Secondly, is there a plan to look at other package managers? What's on my mind is: why npm over bower? What advantages do you see that npm brings to working with css that bower cannot provide? Also, I'd be curious as to how it all works with pre-processors.

**Comment by sethvincent** [comment]
Hey @misscs, good questions. 

I kept the original description vague about the specific tools ([rework-npm](http://npmjs.org/rework-npm), [npm-css](http://npmjs.org/npm-css), [insert-css](https://www.npmjs.com/package/insert-css), etc.) because I plan to cover a few different approaches. I'll make a revision to the description to make that more clear.

I haven't used bower for a while. There are approaches for doing things with bower that are similar to the tools I'll cover (example: [wiredep](https://www.npmjs.com/package/wiredep)), but I've yet to find a method with bower that's as easy as the approach that rework-npm uses. I'd also rather use npm for both CSS & JS dependencies. 

And that's one of the main advantages: I don't have to use bower when I can use the same tool for installing, updating, and publishing both CSS & JS.

About preprocessors: sometimes a tool like rework-npm is a dependency of the preprocessor, so it's being used internally. Other times, you can do the step of importing css packages first, then run the pre-processor. For example I'll sometimes do that with a command like this using the pre-processor [myth](http://myth.io):

```
rework-npm source.css | myth > bundle.css
```

**Comment by jasonrhodes** [comment]
I love the idea of this talk. Suggest `npm install css` or something similar for the title, perhaps? :)
