### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by davethegr8** [cascadiajs/2015.cascadiajs.com#24]
Ship initial splash page for website. This will establish base look & feel for the site and cjs2015. Should also give us a good starting point for the rest of the site.

Evolve the design/brand of previous years, and something summer + pacnw + beach would be ideal. 

To keep in mind for design, a challenge will be to present the 3 different days as a cohesive conference but with the ability for each day to have its own site/page/subsection that the Curator has creative freedom.

Things we like:

- 2015 ember conf: http://emberconf.com/ ![emberconf_2015_-_2015-01-09_09 10 20](https://cloud.githubusercontent.com/assets/55392/5683756/5d23b364-97df-11e4-921e-85de5c652b47.png)
- https://www.jsconfar.com/ (interactive, has a game and a terminal)

**Comment by davethegr8** [comment]
Proposed: (by @zachattack)

![splash-ver01](https://cloud.githubusercontent.com/assets/55392/5771208/428b8e1a-9ced-11e4-9fcb-0b4dccbf244e.jpg)

**Comment by hackygolucky** [comment]
The color scheme looks great, @zackattack Very classy. Excited to see a little more copy and maybe a subsection or two so we can see how the layout works out. Copy will be ready by Sunday!

**Comment by jden** [comment]
what I love about the dark header image is that it's woodsy and looks like there could be a sasquatch behind any of those trees. or a PNW giant tree octopus. or a boreal cephalopod. (what say ye, @nvcexploder)

**Comment by nvcexploder** [comment]
I think the dark looks great also, especially woodsy! If we could incorporate boreal cephalopods  or the PNW GTO I might lose my mind!

**Comment by davethegr8** [comment]
Latest, will launch soon

![cascadiajs_fest_2015_-_2015-01-23_14 28 47](https://cloud.githubusercontent.com/assets/55392/5883973/55d4ed2a-a30c-11e4-94f4-74f00ce5f340.png)
