### ISSUE TITLE
Artisanally-Crafted Testing Toolbelts

### ISSUE THREAD

**Issue by pamo** [cascadiajs/2015.cascadiajs.com#258]
* Names: Pamela Ocampo & Pete Hodgson
* Location: San Francisco, CA
* Emails: pamo@thoughtworks.com & phodgson@thoughtworks.com
* Twitter: [@pmocampo](http://twitter.com/pmocampo) &  [@ph1](http://twitter.com/ph1)
* GitHub: @pamo & @moredip
* Url(s): [likescoffee.com](http://likescoffee.com) & [thepete.net](http://thepete.net)

## The story you'd like to tell

Writing high quality, maintainable client-side code is becoming increasingly important as we continue to move more logic into the browser. In addition, we have many test tools and libraries to choose from. Each set of tools gives us different benefits and imposes some disadvantages to test driven development. During this talk we will cover the pros and cons we experienced when using Jest, Facebook's packaged testing library, versus rolling a custom set of tools for testing Javascript. After Pam and Pete cover the advantages and disadvantages, they will give attendees an overview of what works best on small projects or at scale from the perspective of two developers in different stages of their careers.

## Speaker Bios

![Pamela Ocampo - caffeinated coder](https://cloud.githubusercontent.com/assets/784889/6632859/ba317374-c8fa-11e4-8003-d3640d436f79.png)

Pam is a full-stack software developer at ThoughtWorks with 3 years of software development experience. She's passionate about learning and adding value to teams and products by introducing new ways of thinking to users. She gets excited when she can work alongside users to get continuous feedback about what she's building. The world of Javascript front-end development allows her to test new ideas quickly by shortening the feedback loop.

Pam loves lifting heavy weights, climbing rocks, riding bikes, coffee culture and will often make an adventure out of finding a good cup of coffee.

![Pete Hodgson](https://cloud.githubusercontent.com/assets/784889/6632814/f1a7a2ca-c8f9-11e4-9238-91b01ea9dfef.png)

Pete is a Lead Consultant at ThoughtWorks with 8 years in the software industry with a focus on mobile development in the last 2. He helps teams get more awesome at delivering maintainable software at a sustainable pace, using agile practices like test-driven design, pairing and continuous delivery. As well as test-driven JavaScript he's also a fan of functional programming, Conway's Law, dynamic languages, hypermedia API design, and brewing his own beer.

**Comment by KatieK2** [comment]
Hi Pam & Pete, I'm part of the Browser JS talk review committee. This is an interesting proposal; thanks for sending it! It would be helpful to understand how this talk benefits from two presenters. We have had one past talk "Hacking Mentor.js" from last year which did really benefit from the approach.
If you're going to make updates, I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thank you!

**Comment by pamo** [comment]
Hey @KatieK2 we think this talk would benefit from both @moredip and me speaking about our experiences given our difference in time in the industry. We would each be talking about the different approaches and how we used the tools that we picked.
