### ISSUE TITLE
Advanced 3d objects in CSS

### ISSUE THREAD

**Issue by pixelass** [cascadiajs/2015.cascadiajs.com#297]
# Advanced 3d objects in CSS

* Name      : Gregor Adams
* Location  : Munich Germany
* Email     : greg@pixelass.com
* Twitter   : [@GregorAdams](https://twitter.com/GregorAdams)
* GitHub    : [pixelass](https://github.com/pixelass)
* Url(s)    : [codepen](http://codepen.io/pixelass)
* previous talks: 
  * https://www.youtube.com/watch?v=fjcOe4sYErk
  * https://www.youtube.com/watch?v=hXTRISz5q_Q

## The story you'd like to tell

In this talk we will learn about the third dimension and what we can create with it and CSS. Different from before seen techniques you will learn how to use the `clip-path` property (currently supported by webkit and blink) to create vector-like shapes with CSS and animate between different shapes or versions of a shape. Furthermore we will discuss the advantage and disadvantages of this technique. After a short guide on the basics of 3d CSS I will show a few advanced shapes like polyhedra, spheres and a torus and explain how we can easily create these shapes with a few SCSS-mixins and a little logic. THIS IS A BRAINBREAKER!!!
Here are some examples of things I have created in 3d CSS: [http://codepen.io/collection/EGHpJ/](http://codepen.io/collection/EGHpJ/), [http://codepen.io/collection/qKeol/](http://codepen.io/collection/qKeol/)
![screen shot 2015-03-15 at 20 25 30](https://cloud.githubusercontent.com/assets/1148334/6657610/9fda1978-cb51-11e4-91d0-8d7809575a14.png)

## Speaker Bio

![gregor_adams_256 copy](https://cloud.githubusercontent.com/assets/1148334/6177584/33ab3982-b308-11e4-9f36-d36ba189cbac.png)

Gregor Adams is a self-taught web developer with a strong focus on CSS. He works as a front-end developer and architect at [SINNERSCHRADER](http://sinnerschrader.com).  
Gregor is very active on [codepen](http://codepen.io/pixelass/) where he shows a lot of abstract CSS experiments. While he has no special focus when is comes to CSS his most impressive works are related to 3d shapes or fractals.  
Gregor speaks at conferences and meetups with a strong urge to teach or help other developers. He pushes his own limits every day, staying up to date with the latest specs, finding fixes for browser quirks or trying to do the impossible.

**Comment by leeluolee** [comment]
I come here  by searching  "clip path 3d" in github .   @pixelass  , I just create a more advanced example at https://github.com/leeluolee/clip3d  which is totally dependent on "clip-path", and without any transform property  . [Demo on codepen](http://codepen.io/leeluolee/pen/KwJbov?editors=101)

**Comment by pixelass** [comment]
@leeluolee it looks interesting. I have to look at it in detail when I find the time. thx for sharing.
`clip-path` is very powerful and I enjoy working with it. It opens a whole new set of possibilities and works well with mathematically calculated shapes.
