### ISSUE TITLE
Title TK!!!

### ISSUE THREAD

**Issue by charliepark** [cascadiajs/2015.cascadiajs.com#34]
#Title of Talk

* Name      : Jane Doe
* Location  : Cascadia, USA
* Email     : janedoe@alltheemails.com
* Twitter   : [@janedoe][url to twitter account]
* GitHub    : [janedoe][url to GitHub account]
* Url(s)    : [jane.doe.com][url to relevant sites]

##The story you'd like to tell

[Presentation description goes here. Try to keep it under say, 500 words, but more than 140 characters]

##Speaker Bio

![](url to avatar image goes here)*avatar is required*

I'm an example bio. I'm a magical sloth that likes to crawl and climb through the forest and sit in the stream and I write code sometimes.

**Comment by jden** [comment]
Hi, it looks like you just copy and pasted the proposal template. You have plenty of time still to get your proposal submitted. In the mean time, I'm going to close this issue. Please open another issue if you'd like to submit a proposal.
