### ISSUE TITLE
You're a programmer

### ISSUE THREAD

**Issue by xzyfer** [cascadiajs/2015.cascadiajs.com#348]
# You're a programmer

* Name      : Michael Mifsud
* Location  : Melbourne, Australia
* Email     : xzyfer@gmail.com
* Twitter   : [@xzyfer](https://twitter.com/xzyfer)
* GitHub    : [xzyfer](https://github.com/xzyfer)

## The story you'd like to tell

The story of how weeks of taunting from non-sensical compiler errors and a supportive community turned this "lowly" frontend developer into a core contributor to Libsass - a large C/C++ project/

Why? Because all too often we see the subtext that "frontend developers aren't real programmers". I see this idea propagating through our industry, and worst of all, into the hearts and minds of fellow frontend developers.

Whether you write CSS, JavaScript or COBOL you're a programmer. It's not our languages that define us but our willingness to learn to master our domain.

I have dabbled in many programming languages over the years. It's all just variables, conditionals and functions right...?

With that in mind October last year, having never written a line of C/C++ that compiled, I was fortunate enough to became a core committer to Libsass. Like many others I found C++ was intimidating - the realm of _real_ programmers - but I had a problem that needed solving.

- A unique syntax
- Linkers and compilers
- Makefiles
- Binaries
- Strict typing
- Forward declarations

Are just a few of the things I needed to come to grips with, and did so by relating them to their frontend counter parts.

I want the audience to leave inspired to step out of their comfort zone, try something new and crazy, and know that failure the hardest and yet most rewarding part of being a _real programmer_.

_If the speaking slots are long enough I think it'd be rad to live code and deploy a Libsass feature in front of a live studio audience_.

## Speaker Bio

![untitled-1](https://cloud.githubusercontent.com/assets/579928/6665162/733b1dd4-cc2a-11e4-86c8-0b9f6050485b.png)

Michael Mifsud is a fullstack engineer at 99designs focusing primarily on frontend and tooling.
He's a big believer in open source and the importance of community in all things. He's a core contributor to Libsass, and an organiser of [CSSConf AU](http://cssconf.com.au) and the [MelbCSS](http://www.meetup.com/MelbCSS/) meetup.

**Comment by xzyfer** [comment]
I think it'd be super rad to some live coding and ship a Libsass feature _in front of a live studio audience_.

**Comment by louisnk** [comment]
If you're going to do that, you should definitely mention it in your proposal - when they review all the submissions that's the only part guaranteed to be read.

I think everyone can agree shipping a feature live would be super rad. I think the talk, even without live coding would be great!

**Comment by xzyfer** [comment]
Thanks @louisnk. I wasn't sure if editing the CFP at this point was legit. Figured I'd add it as an aside.

**Comment by davethegr8** [comment]
For what it's worth, I think proposals are essentially locked that this point. The reviewers are going through all the talk submissions now. I believe they downloaded all the issues on March 16th, so I'm not sure if making any changes at this point will have an effect.

**Comment by xzyfer** [comment]
Good to know. Makes sense. Wasn't sure what the process was.

**Comment by davethegr8** [comment]
Yeah, no worries. I'm not 100% sure of the review process since I'm not on the review committees, but I believe final decisions will be ready on April 15th.
