### ISSUE TITLE
Talk: It came from Web Components

### ISSUE THREAD

**Issue by thomaswilburn** [cascadiajs/2015.cascadiajs.com#36]
# It came From Web Components (or: custom elements in production)

* Name      : Thomas Wilburn
* Location  : Seattle, WA
* Email     : news@thomaswilburn.net
* Twitter   : [@thomaswilburn][https://twitter.com/thomaswilburn]
* GitHub    : [thomaswilburn][https://github.com/thomaswilburn]
* Url(s)    : [thomaswilburn.net][http://thomaswilburn.net]

## How the Seattle Times uses custom elements to deliver news apps

Web Components have gotten a lot of press lately, especially given high-profile frameworks like Polymer, but relatively few people have deployed them in production. That's a shame, because unlike some modern browser APIs, they're perfectly usable in browsers today, and the developer benefits can be substantial. At the Seattle Times, we see web components--and particularly custom elements--as powerful tools for building news apps and interactive stories, and we're already using them in production code.

In this presentation, we'll talk about how to polyfill the web component spec for use in modern browsers and IE9+. We'll discuss how custom elements can make developer's lives easier and speed project development. And we'll look at some existing, high-traffic Seattle Times projects that are already using these techniques to great effect. By the end of the talk, you'll be prepared to go forth and make fast, easy, reusable web components of your very own.

## Short talk outline

1. Intro to Web Components
  - What are they?
  - How do they save time? What are the benefits?
2. Case studies:
  - `<leaflet-map>` lets our producers quickly assemble data-driven maps without writing JavaScript
  - `<responsive-frame>` is built into our new CMS for injecting external content responsively
  - `<svg-map>` for our elections, made SVG much less painful
3. Building a web component on the current web platform
  - Tech used: `document.registerElement()` shim, LESS, DoT templates, Browserify
  - Construct a `<markdown-preview>` element in five minutes.

## Speaker Bio

![](https://avatars2.githubusercontent.com/u/881329?v=3&s=256)

Thomas Wilburn is the news web developer for The Seattle Times, where he works with editors and journalists to tell stories in web-savvy digital formats. Previously, he worked on the web team for Guild Wars 2 at ArenaNet. He's also the author of Caret, an open-source, Sublime-like editor written as a Chrome packaged app.

**Comment by othiym23** [comment]
Web Components in the real world? I am very interested.

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. A lot of folks are interesting in hearing about production use of web components. It would be useful to know which polyfills / solutions you are planning on covering. Thanks for your proposal!

**Comment by thomaswilburn** [comment]
We're using the following polyfills/platform substitutes currently:

- Custom elements - Andrea Giammarchi's `document.registerElement` shim
- HTML imports - Browserify packaging with plugins for requiring text
- Shadow DOM - well-scoped LESS
- Templates - DoT.js

I think my general outline would be to first talk about the tech in overview, demo a few of our custom elements in practice, then introduce our shim/polyfill stack and walk through setting up a simple element.

**Comment by KatieK2** [comment]
@thomaswilburn  Cool, thanks! I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - everyone is guaranteed to see.

**Comment by thomaswilburn** [comment]
Will do, Katie, thanks!
