### ISSUE TITLE
Talk: The Design of Developing

### ISSUE THREAD

**Issue by jefflembeck** [cascadiajs/2015.cascadiajs.com#37]
# The Design of Developing

* Name      : Jeffrey Lembeck
* Location  : Seattle, WA, USA
* Email     : jlembeck@gmail.com
* Twitter   : [@jefflembeck](http://twitter.com/jefflembeck/)
* GitHub    : [jefflembeck](https://github.com/jefflembeck)
* Url(s)    : [jefflembeck.com](http://jefflembeck.com)

As front-end developers we hear a lot about the design of the interfaces we’re building. But what about the design of our dev tools? Strong design principles can transform one-off scripts into something more modular, more reusable, and more accessible to a broader audience: in other words, design principles can transform our code into software. In this talk I'll use my experience building open source tools—utilities such as Grunticon and CriticalCSS—to show how you can transform your idea into a well-made, maintainable tool that will hold up for as long as you need it.

## Speaker Bio

![Jeff's Face](https://jlembeck-monosnap.s3.amazonaws.com/jeff-face-256.png)

Jeff Lembeck is a developer over at [Filament Group](http://www.filamentgroup.com). He writes a whole lot of code and the occasional post for [A List Apart](https://www.alistapart.com/), has guest lecturered and TA'd for [Ada Developers Academy](http://adadevelopersacademy.org), and is a former member of the jQuery Mobile team. Jeff lives in Seattle where he obsesses over oyster happy hours and how to make the best negroni. He dreams of someday owning a hot tub boat.

**Comment by misscs** [comment]
:+1: for building tools. I'd be interested in hearing this talk.
