### ISSUE TITLE
Make Reporting app public-friendly

### ISSUE THREAD

**Issue by hackygolucky** [cascadiajs/2015.cascadiajs.com#392]
Sharing tools like the awesome reporting app is a great way to give back to the community at large. I think there's a few steps we'll need to make that happen, and please add your thoughts!
- Build out the docs for people who are new to Twilio and test them out with someone who has never seen it. Reference the reporting guidelines and CoC that makes sure people know it's an ecosystem of safety, not a stand-alone tool.
- move to a separate repo in the Cascadia org for better discoverability
- share it everywhere! (maybe write a post on the good/bad/improvements for people to see what they can expect and help make better)

cc @davethegr8 @crtr0

**Comment by davethegr8** [comment]
All of that:

http://fitfulfocus.com/wp-content/uploads/2015/02/leonardo-dicaprio-celebrate-gif.gif

Logistically, I'd like to get a beta test(er) to help identify and iron out kinks. I've already got someone in mind.

I'd also like to be able to deploy on BlueMix for non-technical folks: https://hub.jazz.net/tutorials/devopsweb/

And finally, there was other interest from people that I spoke with at the conf about making it available in different ways. Will share more at our f2f postmortem.
