### ISSUE TITLE
Talk: You have the node hammer, don't make everything a nail!

### ISSUE THREAD

**Issue by nesQuick** [cascadiajs/2015.cascadiajs.com#41]
# You have the node hammer, don't make everything a nail!

* Name: Ole Michaelis
* Location: Hamburg, Germany
* Email: ole.michaelis[at]googlemail.com
* Twitter: [@codestars](https://twitter.com/codestars)
* GitHub: [nesQuick](https://github.com/nesQuick/)
* Url(s): [codestars.eu](http://codestars.eu/)

## The story you'd like to tell

node.js is a great tool. Just like a hammer is a great tool too. Used correctly it can archive so many great things. But once you have that hammer, everything looks like a nail. **node.js just sucks when it comes to building websites**, but it's a great tool for small network based services within a heterogene micro service architecture. I want to show where we ([*Jimdo*](http://www.jimdo.com/)) use node.js in our distributed architecture, and where and why we decided to go with other languages / frameworks.

## Speaker Bio

![](https://avatars0.githubusercontent.com/u/584259?v=3&s=256)

Ole Michaelis is the co-founder of SoCoded, a hackfest and web development conference in Hamburg. He’s a Software Engineer at Jimdo, a DIY website creator, where he focuses on backend development. In his free time, he’s building slidr.io, a hazzle-free slide sharing platform. Ole is passionate about open source software, enjoys traveling, and loves Mexican food. He classifies himself as a 'bad' German as he dislikes beer and soccer – the traditional German past-times.

**Comment by ryan-roemer** [comment]
Hi Ole, I'm part of the Server JS day review committee. Could you flesh out some more details about Jimdo in terms of what it's doing and why that's good / desirable / interesting to Node.js / web applic developers? Thanks!

**Comment by nesQuick** [comment]
@ryan-roemer I'm totally sorry for the delay. Frankly, I have to withdraw my application, because other things came up. I still do want to answer your question very shortly:

Jimdo as a company is around for ~7 yrs. Grown codebase for the last years. Now we are trying to split microservices out of it. My team is running the very first service, and also trying to extract more. Jimdo is a DIY website builder.

I hope, we can arrange something next year :tada:
