### ISSUE TITLE
Autoresponder for speak@cascadiajs.com?

### ISSUE THREAD

**Issue by GregBulmash** [cascadiajs/2015.cascadiajs.com#42]
Since I've done the github route, I thought I'd shoot in my pitch via the email route.

With GitHub I can track my proposal, even make edits. But with the mail route, I send it winging off into the ether... 

It would be nice if we added an autoresponder on that address saying "thanks, we got your e-mail and will be getting back to you once we have reviewed all the proposals. If you need to speak to us about X, Y, or Z, please use these contact points: [list of contact points]"

**Comment by oncletom** [comment]
And to notify people before closing the proposal issues? It is rather cold to see 4 notifications of closed issues without a single word, not even a 'thanks for taking the time to contribute but…'.

**Comment by crtr0** [comment]
Hey @oncletom, you should have received an email from us. Can you check your inbox/spam/etc? I've very sorry if this is how you heard the news. I would be frustrated as well :/

**Comment by hackygolucky** [comment]
howdy @oncletom, You might want to check your spam filter. I just reconfirmed that we did send you a decline letter.

**Comment by stefanjudis** [comment]
@hackygolucky Hmm, just checked my spam. Wasn't anything in there. So closed means declined, right? 

No problem though. :)

**Comment by hackygolucky** [comment]
Yeah, you were on our spreadsheet list of declines, but I just checked the
mailer we used to email you(that hopefully keeps the email out of spam) and
for whatever reason it cleaned your email out of that list. Sorry about
that. :-/

**Comment by stefanjudis** [comment]
@hackygolucky No problem. Thanks for quick response.

**Comment by oncletom** [comment]
Probably felt into a similar caveat as I got no email whatsoever; either in archives, inbox ou spam.
No worries though, the programme looks rad and I can only wish you an excellent festival altogether :-)

**Comment by KatieK2** [comment]
I've created an issue to tracking good idea for next year: https://github.com/cascadiajs/2015.cascadiajs.com/issues/386 . Any objections to closing this issue?

**Comment by oncletom** [comment]
:+1:
