### ISSUE TITLE
Talk: Automating testing, documentation and validation with schemas in hapi

### ISSUE THREAD

**Issue by ptte** [cascadiajs/2015.cascadiajs.com#43]
# Automating testing, documentation and validation with JSON schema in hapi

* Name      : Patrik Ring
* Location  : New York, USA
* Email     : patrik.ring@gmail.com
* Twitter   : [@patrikring](https://twitter.com/patrikring)
* GitHub    : [ptte](https://github.com/ptte)
* Url(s)    : [patrik.io](http://patrik.io)

We started building services on HAPI a year back and found it to be a great framework. Since then we have added some plugins to our stack for automatically connecting all endpoints to rabbitMQ, supporting validation of input and output streams via schemas, simplify integration testing and much more.

One of the things we wanted to achieve was to automatically generate documentation for our different endpoints/services.

JOI is very simple to use but it lacks in how it lets you describe your data, so we started writing schemas in yaml. We allow for the whole range of validation structures that's supported by the JSON schema standard. It also makes it possible to add meta data around the data we're describing, so as to make automatic documentation and testing of endpoints more elaborate, and easier.

I want to tell you about how this helps us build faster, and provide more robust apis.

Added as per @nvcexploder recommendation:
Documentation can either be "manually" generated our easily built into a build step. We solve this using jenkins, and we have a separate project for the documentation generation that unfortunately isn't quite ready for open source, but we're getting there.

We are working a lot with regards to rabbitmq and having that be an important backbone for communication between internal services. We have a library for easy access from both node js apps and PHP (which still makes for part of our code base) which makes it seamless to talk to other app just as if they were normal in process calls (although they also add async support for php which is pretty neat).

We are also focusing on the testing, schema and docs. They're both important focuses and we have some interesting progress in for example our project lintlovin (https://github.com/bloglovin/lintlovin) which works really well together with our schemas and test structure (or with pretty much any other node project).

## Speaker Bio
![Patrik Ring](https://cloud.githubusercontent.com/assets/915479/5916782/3755ab8a-a615-11e4-8bac-cc3036739802.png)

Patrik Ring is the CTO and founder over at Bloglovin.com, and he loves writing code, which he primarily does in javascript or php. Main interests are backend and dev-ops. Patrik thinks that diversity is extremely important for successful teams and spends time reading a lot on the issue, including going to alterconf and other wonderful events.

When not involved in social justice or computers, he enjoys rock climbing, skiing and parkour.

**Comment by nvcexploder** [comment]
Howdy! I'm on the review committee for server day, and was wondering is the automated documentation based on a build step or at runtime (or both! :) ). Also, do you plan on going more into your stack (the RabbitMQ auto-connecting stuff) or just focusing on the testing, schema, and docs?

**Comment by ptte** [comment]
@nvcexploder Hi!

I was out skiing so a little slow here.

Documentation can either be "manually" generated our easily built into a build step. We solve this using jenkins, and we have a separate project for the documentation generation that unfortunately isn't quite ready for open source, but we're getting there.

We are working a lot with regards to rabbitmq and having that be an important backbone for communication between internal services. We have a library for easy access from both node js apps and PHP (which still makes for part of our code base) which makes it seamless to talk to other app just as if they were normal in process calls (although they also add async support for php which is pretty neat).

We are also focusing on the testing, schema and docs. They're both important focuses and we have some interesting progress in for example our project lintlovin (https://github.com/bloglovin/lintlovin) which works really well together with our schemas and test structure (or with pretty much any other node project).

Let me know if there is anything else I can provide :)

**Comment by louisnk** [comment]
Hey @ptte,

From watching all these proposals I can say: they're going to ask that you move that clarification into your initial post, since the reviewers will be looking at 220+ proposals and the initial proposal is the only part they're guaranteed to read.

**Comment by ptte** [comment]
Thanks @louisnk
