### ISSUE TITLE
Talk: Having fun with Neopixels & JavaScript

### ISSUE THREAD

**Issue by ykro** [cascadiajs/2015.cascadiajs.com#45]
##Having fun with Neopixels & JavaScript

* Name      : Adrián Catalán
* Location  : Guatemala, GT
* Email     : adriancatalan@elementalgeeks.com
* Twitter   : [@ykro](https://twitter.com/ykro)
* GitHub    : [ykro](https://github.com/ykro)
* Url(s)    : N/A

I love to make&build using RGB LEDs, don't you love it too? they are so bright and full of life! also I happen to like JS very much so why not mix both? Through this presentation we will show several projects made with neopixels including games(tic-tac-toe, tetris), wearables and interactive art.

##Speaker Bio

![](https://avatars3.githubusercontent.com/u/398169?v=3&s=460)

Educator, tinkerer and software developer. Elemental Geeks co-founder, Innovation Lab @ GalileoU lead, Android GDE, NodeBots Guatemala & GDG Guatemala co-organizer. Firmly believer in the power of community. From Galileo University he is trying to empower as many people as possible in latam to become makers. He started Engineering Kickstart a program for high schoolers to get started into coding and basic electronics, to get them excited about tech, let them connect with mentors and make them cross the line from users to makers.

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. This is an interesting proposal! It would be helpful to know how in depth this talk will go into both the hardware and software side of things. 
Looking forward to hearing from you, and thanks for your talk proposal!

**Comment by ykro** [comment]
@KatieK2 Hi Katie, on the hardware side it would include demos with strips, matrices, rings and individual neopixels with the basics of powering the circuits and best practices when working with RGB LEDs. Also, the plan is to work both with Arduino and Tessel (maybe Beaglebone black). On the software side there is some basic JS for the games including collision detection, representation of the game board, etc, API connections for the wearables and audio processing for the interactive part art. 

By the way, I'm working this with a co-worker from my lab, if this talk is selected, would if be possible to co-present? or would you recommend to have only one speaker? thanks!

**Comment by KatieK2** [comment]
Hi @ykro. Most of our talks do only have one speaker. We would want to understand what having a second presenter would to the talk.

**Comment by ykro** [comment]
Hi @KatieK2 sorry for the delay. We are a small team(http://innovacion.galileo.edu/index.php/people/staff) at the lab that I lead, and I'm trying to encourage everyone to be speakers but as it will be their first time doing public speaking in english, Mónica, who is helping me with this project asked if we could present together or if I can do the presentation and she go to the event as attendee and maybe next year she can send a proposal. I think having two speakers can make the talk more interactive and we have done so several times locally as most of our projects are the result of team work :) as a curator you have the experience on what works and what doesn't so we are open to suggestions. Thanks!

**Comment by ykro** [comment]
+ @mcalvarado

**Comment by GregBulmash** [comment]
Is this coding happening in Node or in the browser. Are you creating
browser-based interfaces for controlling the lights.

**Comment by ykro** [comment]
@GregBulmash most of our demos are command line based, it's still a work in progress so we might have something browser based in time for the conference :)
