### ISSUE TITLE
Talk: Using JavaScript to reach the next gen of coders in LATAM 

### ISSUE THREAD

**Issue by ykro** [cascadiajs/2015.cascadiajs.com#46]
#Using JavaScript to reach the next gen of coders in LATAM 

* Name      : Adrián Catalán
* Location  : Guatemala, GT
* Email     : adriancatalan@elementalgeeks.com
* Twitter   : [@ykro](https://twitter.com/ykro)
* GitHub    : [ykro](https://github.com/ykro)
* Url(s)    : N/A

There's a sense of pride in making, in learning something new and seeing it working in real life. Even if it's only blinking a LED(the hardware version of a hello world) there's something magical when it works. That is why we are working in a program called STEAM@UG from GalileoU in Guatemala for high school students as an introduction to coding and basic electronics. 

Using a few simple games like pong, tic-tac-toe, etc is a great way to connect with teenagers interested in tech and let them become makers coding with JavaScript and building basic hardware to control the games.

##Speaker Bio

![](https://avatars3.githubusercontent.com/u/398169?v=3&s=460)

Educator, tinkerer and software developer. Elemental Geeks co-founder, Innovation Lab @ GalileoU lead, Android GDE, NodeBots Guatemala & GDG Guatemala co-organizer. Firmly believer in the power of community. From Galileo University he is trying to empower as many people as possible in latam to become makers. He started Engineering Kickstart a program for high schoolers to get started into coding and basic electronics, to get them excited about tech, let them connect with mentors and make them cross the line from users to makers.

**Comment by othiym23** [comment]
I would like to see this talk.

**Comment by KatieK2** [comment]
Hi again! It would be interesting to know how long the STEAM@UG program has been going. Thanks for submitting another talk!

**Comment by ykro** [comment]
@othiym23 thanks! :smile: 
@KatieK2 Hi! the program started in 2013 as a small pilot with 20 students, last year we got to 150 and this year we are aiming 500. Thanks for your feedback and if you have any other suggestion for the proposal please let me know :)

**Comment by nvcexploder** [comment]
This looks seriously rad. Will you be going into how you got involved in the schools?

**Comment by ykro** [comment]
@nvcexploder thanks! it's more about what we have used as tools and our journey, as this is in Guatemala, the challenges of getting involved with schools are different but regardless of the talk being accepted I'm happy to chat any time about it

**Comment by louisnk** [comment]
I would also like to see this talk.
