### ISSUE TITLE
Talk: These Bots are Made for Walkin'

### ISSUE THREAD

**Issue by dtex** [cascadiajs/2015.cascadiajs.com#47]
# These Bots are Made for Walkin'

* Name      : Donovan Buck
* Location  : Houston, TX
* Email     : donovan@donovan.bz
* Twitter   : [@dtex](https://twitter.com/dtex)
* GitHub    : [dtex](https://github.com/dtex)

## The story you'd like to tell

Johnny-Five's new [Animation class](https://github.com/rwaldron/johnny-five/wiki/Animation) gives us the ability to sequence complex movements across multiple servos. What's that good for? Walking robots of course! 

This talk is follow up to Rick Waldron's [Bits of Nodebots Next](https://www.youtube.com/watch?v=0-6_iA1zZDk). We've moved the mark from "This is possible in Johnny-Five!" to "This is built into Johnny-Five!" and we want to everyone to build really cool, creepy, crawly things with it.

This talk includes a brief introduction to Johnny-Five, robot gaits and kinematics along with tips to get you started with the Animation class and Johnny-Five.

## Speaker Bio

![](http://www.brandextract.com/content/includes/bethumbs/images/people/donovan_buck/w256/h256/portrait.jpg)

I am a Johnny-Five collaborator, and an amateur roboticist. 

This is an updated version of the [talk I gave at EmpireNode](https://www.youtube.com/watch?v=yNi3IPkTOos). It includes a little more on robot gaits, additional demos and a little less walking through code.

**Comment by nvcexploder** [comment]
Howdy @dtex! I'm one of the reviewers for server day @ Cascadia. I remember your talk at Empire Node, it was rad! Are the additional demos with the bot that you had there (I'm assuming so)?

**Comment by dtex** [comment]
Hi @nvcexploder ,

Yes, it's all on the same robot. I was able to get IK working while at RobotsConf which led to smoother sequences and more interesting movements. 

Thanks for the praise. I remember wishing I was as comfortable on stage as you seemed.
