### ISSUE TITLE
Talk: Browser Video Collaboration with WebRTC and ObjectRTC, No Plugins Needed

### ISSUE THREAD

**Issue by reybango** [cascadiajs/2015.cascadiajs.com#48]
# Browser Video Collaboration with WebRTC and ObjectRTC, No Plugins Needed

* Name      : Rey Bango
* Location  : Florida, USA
* Email     : reybango@gmail.com
* Twitter   : [@reybango](https://twitter.com/reybango)
* GitHub    : [reybango](https://github.com/reybango)
* Url(s)    : [Rey Bango](http://blog.reybango.com/)

## The story you'd like to tell

The Open Web Platform has evolved tremendously allowing browsers to provide capabilities previously only available via specialized plugins. WebRTC and the newest specification, ObjectRTC (ORTC), are the evolution of plugin-free video collaboration and in this talk, we’ll go over how these specifications will change the way we collaborate on the web.

We’ll look at:

- The current state of WebRTC
- How to leverage WebRTC now
- The differences between WebRTC and ORTC
- What ORTC will bring to the table, why it's important and how to plan for the future

I'll also be doing coding to demonstrate WebRTC usage.

## Speaker Bio

![](http://reybango.com/pics/rey-256.png)

Rey is a developer advocate at Microsoft focused on helping developers build awesome cross-browser experiences. He’s an ardent supporter of standards-based development and a former member of the jQuery Project Team.

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. This is an interesting proposal! It would be useful to know a little more detail about how this talk would evolve from previous CascadiaJS talks on WebRTC. Thanks for your talk proposal!

**Comment by reybango** [comment]
@KatieK2: thanks for checking in. So Henrik's presentation was awesome and he gave a fantastic overview of WebRTC. I want to go a little farther than what he did and demonstrate how to actually leverage it in code as well as discuss how ORTC, the new RTC spec, will impact development.

I expect to offer an overview of where WebRTC is at, how ORTC will affect the future, and how to plan for the future. I'll also be doing coding to demonstrate WebRTC usage.

**Comment by KatieK2** [comment]
@reybango Cool, thanks! I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - everyone is guaranteed to see.

**Comment by reybango** [comment]
@KatieK2 Sure thing. Updated. let me know if that looks better.

**Comment by TheAlphaNerd** [comment]
This looks really cool.  I have not heard much about ORTC and would love to know more.

**Comment by reybango** [comment]
Thanks @TheAlphaNerd. Lots of people are pumped about it and I hope to be able to share that. :)
