### ISSUE TITLE
Talk: What's new with Babylon.js v2.0

### ISSUE THREAD

**Issue by deltakosh** [cascadiajs/2015.cascadiajs.com#49]
# What's new with Babylon.js v2.0

* Name      : David Catuhe
* Location  : Seattle, USA
* Email     : davca@microsoft.com
* Twitter   : [@deltakosh](http://www.twiter.com/deltakosh)
* GitHub    : [deltakosh](https://github.com/deltakosh)
* Url(s)    : [EternalCoding](http://blogs.msdn.com/eternalcoding)

## The story you'd like to tell

Babylon.js is a free open source framework (www.babylonjs.com). Version 2.0 will introduce a lot of interesting features:
- WebAudio support
- Automatic scene optimization
- Procedural textures
- Hardware nstances and LOD

This session will cover how these features are working, alongside a deep dive into the debug layer, a new tool that allows web developers to leverage F12 tools in order to understand well how different parts of the engine are interacting together.

Key points:
- You do not need to know Babylon.js to come to this talk as I'll focus on new and independent stuff (like web audio for instance)
- Every sample and code will start from the playground (www.babylonjs.com/playground) where you do not need any expertise on babylonjs
- The F12 part is all about window.performance.measure API that I integrated into Babylon.js to get a more visual result (more info here: http://doc.babylonjs.com/page.php?p=22611)

In a more general way, Babylon.js v2.0 is a way to use advanced 3d topics without the burden of learning all the plumbing :)

## Speaker Bio

![](https://pbs.twimg.com/profile_images/542068500789862400/f2UVZyBT.jpeg)

David Catuhe is driving HTML5 and open web standards evangelization for Microsoft. He defined himself as a geek. He loves developing with JavaScript and HTML5 but also with DirectX, C#, C++ or even Kinect (He wrote a book about it which is available on Amazon). He is the author of Babylon.js (www.babylonjs.com) and hand.js (handjs.codeplex.com).

**Comment by KatieK2** [comment]
Hi David, I'm part of the Browser JS talk review committee. It would be helpful to understand how useful this talk would be to attendees who aren't using Babylon, as well as a little more detail about the F12 tools.
Thanks for your proposal!

**Comment by deltakosh** [comment]
Hey sure thing.
- You do not need to know Babylon.js to come to this talk as I'll focus on new and independent stuff (like web audio for instance)
- Every sample and code will start from the playground (www.babylonjs.com/playground) where you do not need any expertise on babylonjs
- The F12 part is all about window.performance.measure API that I integrated into Babylon.js to get a more visual result (more info here: http://doc.babylonjs.com/page.php?p=22611)

In a more general way, Babylon.js v2.0 is a way to use advanced 3d topics without the burden of learning all the plumbing :)

**Comment by KatieK2** [comment]
Cool, thanks! I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - everyone is guaranteed to see.

**Comment by deltakosh** [comment]
Done :)
