### ISSUE TITLE
A place for workshops within the CascadiaJS event schedule

### ISSUE THREAD

**Issue by hackygolucky** [cascadiajs/2015.cascadiajs.com#5]
*I've seen some conferences do really rad stuff with incorporating workshops as part of their main event schedule. LXJS is a great example. JSConf is another approach.*

**Would people want this?**
Most attendees were so so excited to sign up for workshops. The topics ranged from browser-side to hardware. All, surprisingly, had almost perfect balance of sign-ups.

**What does it take to implement?**
- ?? number of workshops
- ~30 attendees per event. 
- 5 instructors--1 leader is part of this set
- as interactive as possible. Collaborative with table neighbors. Possibly moving around doing things. Fresh topics.
See more below.

**How can it be better?**
Lots and lots of awareness. This is a mini-conf in itself. As curator, you cannot assume everything is taken care of by anyone running these individual workshops. This goes as far as audio or office supplies on the day-of.

**Workshops should absolutely not be product pitches.** Most of EmpireNode's workshop proposals were disguised pitches. When we investigated this more it was disappointing. That's not why people attend workshops. Twilio and Hapi.js(sort of Walmart even they though are working to separate these concerns) are the few companies/projects I've seen do workshops without 'selling' to me. That's important. Attendees will smell that quickly.

**My experience with running workshops so far:**
You should have an owner of Workshop Wrangler. This person needs to not only be responsible for driving the Call for Workshops, but will have to educate the community on what is really being sought out for this event. You can write it all down and publish it on the Call for Workshops and on the website. That won't be enough. It's a lot of in-person recruiting and networking. To get the results you want, you may have to come up with the workshops you want--premise, basic expectation of what will transpire, and what you'll want the attendees to walk away knowing/feeling. You will need to have an absolute deadline for all content for the workshop, because it requires a run-through prior for quality control. There can be no movement on this.

The workshops should be varied. They don't need to all be beginner friendly. In fact, I would highly discourage it. They do require having teams of instructors who are friendly and patient. We were very fortunate that those who agreed to instruct were just insanely wonderful people.

**Comment by TheAlphaNerd** [comment]
I would love to help out with this from both a curatorial stand point as well as a content creation standpoint.  My job involves throwing all sorts of impromptu workshops for javascript, and one thing I have found many participants requesting afterwards is a "Intro to JS" workshop.

It is very possible that this is not the case for Cascadia, as most participants are probably a little more on the senior side.

Nodeschool is always a great fall back, the last node-conf did a great job of making all of the workshops nodeschool courses.  While this is not appropriate for all workshops, it was a great way to document and share the workshops to be used in the future.

**Comment by jasonrhodes** [comment]
As @hackygolucky already knows, I ran the NodeSchool workshop for Empire Node and we had a great time and what seemed to me to be a great response. Mostly thanks to having just an amazing group of mentors. I wish I'd been a little more prepared in advance than I was, but it seemed like a great way to mix up the conference set up.

I also think some kind of JS Fundamentals or Refresh.JS however you want to brand it could be interesting...

**Comment by othiym23** [comment]
Nodeconf 2014 followed an all-workshop(per) format, and while the feedback was mixed (I think some attendees really felt the lack of traditional presentations), I think it works really well as a component of a larger conference. Also, I enjoy facilitating sessions and acting as a mentor, as it's a more direct way to interact with other participants -- which is good, because as @jasonrhodes implies, it's a lot of work. So I'm down to help out with this (assuming CascadiaJS doesn't conflict with NodeconfBR, which is the first week of September).

**Comment by stevengill** [comment]
I could do a half day workshop on building mobile apps with cordova/phonegap!

**Comment by KatieK2** [comment]
We have workshops! :) Closing this issue.
