### ISSUE TITLE
Talk: AngularCDC - Seamlessly connect your angular.js app to any online data source

### ISSUE THREAD

**Issue by deltakosh** [cascadiajs/2015.cascadiajs.com#50]
# AngularCDC - Seamlessly connect your angular.js app to any online data source

* Name      : David Catuhe
* Location  : Seattle, USA
* Email     : davca@microsoft.com
* Twitter   : [@deltakosh](http://www.twiter.com/deltakosh)
* GitHub    : [deltakosh](https://github.com/deltakosh)
* Url(s)    : [EternalCoding](http://blogs.msdn.com/eternalcoding)

## The story you'd like to tell

Angular Cloud Data Connector, or [AngularCDC](http://acdc.azurewebsites.net/) is a library initially built for AngularJS that allows you to work seamlessly with many data sources. AngularCDC supports offline mode and can handle all CRUD operations for you.

This talk will start with a quick glance at the architecture and then some samples with provided providers (AWS, Azure, CouchDB)
 Then to better understand how a provider is working we well create a new one

ACDC is built on top of angular.js but next version will be independent from it and would be usable with Node.js for instance and I would be able to demonstrate the new version during this talk!

## Speaker Bio

![](https://pbs.twimg.com/profile_images/542068500789862400/f2UVZyBT.jpeg)

David Catuhe is driving HTML5 and open web standards evangelization for Microsoft. He defined himself as a geek. He loves developing with JavaScript and HTML5 but also with DirectX, C#, C++ or even Kinect (He wrote a book about it which is available on Amazon). He is the author of Babylon.js (www.babylonjs.com) and hand.js (handjs.codeplex.com).

**Comment by KatieK2** [comment]
This is an interesting proposal! It would be helpful to know a little more about the meat of this presentation, and also what attendees would take away from it if they're not using Angular. Thanks for your talk proposal!

**Comment by deltakosh** [comment]
Hey!
This talk will start with a quick glance at the architecture and then some samples with provided providers (AWS, Azure, CouchDB)
Then to better understand how a provider is working we well create a new one

ACDC is built on top of angular.js but next version will be independent from it and would be usable with Node.js for instance

**Comment by KatieK2** [comment]
@deltakosh OK, cool. I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every one is guaranteed to see. Also, you might want to update this bit: "even you your won online". Thanks!

**Comment by deltakosh** [comment]
sure thing!
