### ISSUE TITLE
Talk: Linux kernel hacking: a crash course

### ISSUE THREAD

**Issue by GeorgiCodes** [cascadiajs/2015.cascadiajs.com#51]
# Linux kernel hacking: a crash course

* Name      : Georgi Knox
* Location  : New York City, USA
* Email     : georgiknox@gmail.com
* Twitter   : [@GeorgiCodes](https://twitter.com/GeorgiCodes)
* GitHub    : [@GeorgiCodes](https://github.com/GeorgiCodes)
* Url(s)    : [geekgirl.io](www.geekgirl.io)

## The story you'd like to tell
Now over 20 year old, the Linux kernel might be one of the most significant pieces of open source software ever developed. The Linux kernel is not magic, but it is millions of lines of code written by thousands of developers so what does it even do? 

This talk will arm attendees with some core knowledge about what the Linux kernel is including system calls, process scheduling, memory management and how the kernel interacts with hardware. We will hack on the kernel and bend it to our will by writing some loadable kernel modules. We will also take a look at some kernel source code and learn how to build our own kernel. 

## Speaker Bio
![](https://us.pycon.org/2015/site_media/media/speaker_photos/RedBProfilePicSml.png.128x128_q85.png)

Georgi is an Aussie software engineer now living and working in New York City. She writes lots of code in all the languages and enjoys dressing her cats up in costumes. Georgi's current nerd crush is on building scalable distributed systems and writing Go. She is an alumna of Hacker School in New York, and currently works in Bitly's Application Engineering team.

**Comment by brycebaril** [comment]
:100: I definitely would love to see this talk!

**Comment by othiym23** [comment]
You could make a whole day out of this (as a workshop) + a presentation on RuntimeJS + a presentation of NodeOS, and it would be super nerdy and exhausting and lots of fun I bet.

**Comment by GeorgiCodes** [comment]
@othiym23 -> Myself and 2 friends will be running an Intro to Linux + Kernel Hacking workshop (4 hours) at CodePalousa I wasn't sure CascadiaJS had tutorials so didn't submit anything like that. Wow RuntimeJS + NodeOS look super awesome - hadn't heard about them :D

**Comment by ryan-roemer** [comment]
@GeorgiCodes -- I'm on the Server JS day talk review committee, but don't really have anything to suggest for this specific proposal before we start reviewing. Separately though, I'm giving a full-stack testing workshop at Code PaLOUsa on the pre-conference day -- would be great to meet up in person.

**Comment by GeorgiCodes** [comment]
@ryan-roemer - Id love to meet up at CodePaLOUsa - my twitter is @GeorgiCodes - please to ping me :)
