### ISSUE TITLE
Talk: Scale all the things: an architecture primer!

### ISSUE THREAD

**Issue by GeorgiCodes** [cascadiajs/2015.cascadiajs.com#52]
# Scale all the things: an architecture primer!

* Name      : Georgi Knox
* Location  : New York City, USA
* Email     : georgiknox@gmail.com
* Twitter   : [@GeorgiCodes](https://twitter.com/GeorgiCodes)
* GitHub    : [@GeorgiCodes](https://github.com/GeorgiCodes)
* Url(s)    : [geekgirl.io](www.geekgirl.io)

## The story you'd like to tell
This crash course is designed to give an overview of scalable web architecture and the open source software that can be used to scale a web application.

This will be a very practical discussion where we will scale an imaginary web application from being a basic single server web app to one that can handle millions of users and terabytes of data whilst maintaining performance and availability. At each step of the journey we will discuss the reasoning behind our decisions and any trade offs we make. 

Topics covered will include decoupling logic through microservices, handling failure through redundancy, horizontal scaling and partitioning of data. We will also go over common open source technologies used for scaling apps such as caching, proxies, load balancers and queues.

Software developers and IT generalists will leave having a general overview of options available to them to effectively scale and manage their web applications using free and open source software and understand the benefits of a range of technologies.

## Speaker Bio
![](https://us.pycon.org/2015/site_media/media/speaker_photos/RedBProfilePicSml.png.128x128_q85.png)

Georgi is an Aussie software engineer now living and working in New York City. She writes lots of code in all the languages and enjoys dressing her cats up in costumes. Georgi's current nerd crush is on building scalable distributed systems and writing Go. She is an alumna of Hacker School in New York, and currently works in Bitly's Application Engineering team.

**Comment by othiym23** [comment]
This is a super ambitious-sounding amount of material to cram into CascadiaJS talk length, but this is alllll material I'd like to see presented.

**Comment by GeorgiCodes** [comment]
Hi Friends! I've decided to pull this submission (as I just don't think id have enough time to prepare for it and it might need a little fine tuning anyway) - Still keen this one fore review: #51
