### ISSUE TITLE
Talk: Your Code is Haunted

### ISSUE THREAD

**Issue by shama** [cascadiajs/2015.cascadiajs.com#54]
# Your Code is Haunted

* Name      : Kyle Robinson Young
* Location  : Portland, OR, USA
* Email     : kyle@dontkry.com
* Twitter   : [@shamakry](http://twitter.com/shamakry)
* GitHub    : [shama](https://github.com/shama)
* Url(s)    : [dontkry.com](http://dontkry.com)

## The story you'd like to tell

Come sit around the campfire and listen to ghost stories about your code. I'll reveal the spooky global and peer dependencies that may haunt your code. We'll dive into the æther exploring global, peer and nested relationships. I'll do some ghost bustin' on how to avoid these unseen specters to maintain a happy and stable project.

**Outline:**

Server/Client Overall Takeaway: *Be mindful of the hidden dependencies that lurk in your code*

* **Global Dependencies**  
  Server/Client Takeaway:  
  *Write modules considering the many available environments your code could be used*
  + What are globals? (maybe ones you forgot)
  + Discuss global architectures
  + Isomorphic consideration (what happens when your same code is ran on the server vs client side and vice versa?)
  + Tour available platforms JavaScript will be ran
* **Peer Dependencies**  
  Server/Client Takeaway:  
  *How to avoid peer dependencies but manage them when you must*
  + What are peer dependencies? (Peer relationships tend to be more hidden than global)
  + Discuss peer architectures
  + The plugin problem (really drive this one showing how updates to peer deps break plugins, maintenance woes)
  + Incompatibile modules
* **Nested Dependencies**  
  Server/Client Takeaway:  
  *Nested dependencies are mostly great*
  + What are nested dependencies?
  + Discuss nested architectures
  + When it's good: most of the time
  + When it's bad: duplication, long path names, disk space, etc
  + Your deps vs their deps (>=2 level deps are not yours)
* **Semantic Versioning**  
  Server/Client Takeaway:  
  *How to best version your modules and that you should semver, even with client side modules*
  + What is semver?
  + How do various package managers interpret semver?
  + Sidenote: Dependencies that you wouldn't think are dependencies, example `^` vs `~` based on the specific version of npm.

## Speaker Bio

![avatar_256](https://cloud.githubusercontent.com/assets/99604/5943258/3b3a0594-a6d2-11e4-8bad-000b45f801ef.png)

Kyle is an open source developer that works for YNAB. He has maintained many spooky projects and ain't afraid of no ghosts.

**Comment by othiym23** [comment]
There are going to be some fun changes happening to `peerDependencies` in npm soon, and it would be good to have somebody helping spread the good word about how to use / not use them properly.

**Comment by shama** [comment]
@othiym23 :+1:

Here is a really rough outline with lots of holes, messy examples and lack of theme applied. I'd really appreciate any feedback though (if not accepted as this talk, I'll release at least as a nice blog post):

## OUTLINE

* Ghost hunt: Global dependencies: "A single instance relationship that is inherited"
  * Node/io: `process`, `module`, `__filename`, `Buffer`, `setTimeout`, `require('stream')`, etc
  * Browser: `document`, `window`, `Object`, `String`, `setTimeout`, etc
  * Node/io example that uses globals:  

    ```js
    // TODO: Need better examples
    var Readable = require('stream').Readable
    var util = require('util')
    function Animal() {
      Readable.call(this)
    }
    util.inherits(Animal, Readable)
    module.exports = Animal
    ```

    Hunt the globals: `require('stream')`, `require('util')`, and `module` are inherently tied to Node/io. Every global, some unlikely, are susceptible to break with each version of Node/io. Consideration is needed for each global used when your code is likely to cross environments: Node to Browser, Browser to Node.

    > TODO: Write examples with cross environment considerations and tools to help

  * Browser example that uses globals:  

    ```js
    // TODO: Need better examples
    function Animal() {
      this.element = document.createElement('div')
      document.body.appendChild(this.element)
    }
    ```

    Hunt the globals: `document`. Every global, some unlikely, are susceptible to break with each browser and version of that browser. Consideration is needed for each global used when your code is likely to cross environments: Node to Browser, Browser to Node.

    > TODO: Write examples with cross environment considerations and tools to help

* Ghost hunt: Peer dependencies: "A single instance relationship that is **not** inherited"
  * You choose your peer dependencies but you can only have 1 instance at a time

    ```shell
    app.js
    node_modules/
      animal_framework@1.0.0
      bear_plugin@2.1.3
      fish_plugin@0.4.5
    ```

    > TODO: Demonstrate a year long life cycle of updates to each module. How plugins react to framework updates and the incompatibilities created during those times. D3 animation tied to theme?

  * Any time an instance is passed into your module, a peer dependency is created:  
    
    ```js
    function Player(game) {
      game.addPlayer(this)
    }
    ```

    `game` is the instance, passing this instance to this plugin creates a peer dependency to `game`. Your plugin is susceptible to break when `game` is updated. Your plugin may not work with other plugins that require different versions of `game`.

    > TODO: Add more examples on how to avoid or minimize the peer dependency impact. Tips: move magic into the app and out of the plugin, create stable (eventually feature locked) interfaces to avoid updates, create a new module instead of breaking an existing (controversial for heavy marketed projects), provide slow upgrade paths, etc.

  * Peer dep by global instances  
    More common with client side code, i.e.: `jQuery`, `Ember`, etc.

    > TODO: Ghost stories with libraries that expect a single global instance. Discuss how sometimes it is unavoidable, i.e.: you only have 1 DOM, 1 event loop

    > TODO: Ghost stories with altering globals and peer dep global instances.

* Ghost hunt: Nested dependencies: "Multiple instance relationships that are not inherited"
  
  > TODO: Discuss more work for the end user initially but less work maintaining the project over time. D3 animation tied to theme?

  > TODO: Code examples building a network of modules that relate to each other without creating peer dependencies.

  > TODO: Duplicate deps and strategies to reduce.

* Semver: Proton pack for battling instability

  > TODO: Discuss semver strategies for battling ghosts, dont cross streams.

  > Sidenote: Discuss usage of `~` and `^` as they are sort of globals, inherited from npm. Explicit dep or peg dep options for the paranoid.

> TODO: Discuss recent changes in npm regarding peer dependencies.

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. Thanks for this proposal! It would be helpful if you could update your main proposal to include the necessary content from your outline; it's always tricky to balance detail with terseness, but your proposal will be better if it tells us what we need to know right in the "story" part. Also, could you clarify the takeaways that front-end developers would expect to get from your talk? Thanks!

**Comment by shama** [comment]
I've updated the story to include a more concise outline with takeaways for both server/client.

Thanks @KatieK2 for your review!
