### ISSUE TITLE
Talk: Staying In The Fast Lane - Tools to Keep Your Site Speedy & Light

### ISSUE THREAD

**Issue by stefanjudis** [cascadiajs/2015.cascadiajs.com#55]
Staying In The Fast Lane - Tools to Keep Your Site Speedy & Light

* Name      : Stefan Judis
* Location  : Berlin, GER
* Email     : stefanjudis@gmail.com
* Twitter   : [@stefanjudis](https://twitter.com/stefanjudis)
* GitHub    : [stefanjudis](https://github.com/stefanjudis)
* Url(s)    : Blog -> [4waisenkinder](http://4waisenkinder.de/)

## The story you'd like to tell

Developing a fast website is not easy. There are plenty of tools and techniques to serve a good and fast experience to our visitors. Monitoring how a site evolves and evaluating and spotting performance bottlenecks is also something everybody should take care of. This talk will give a overview describing which tools are available and why it makes sense to build up a performance culture inside of a company.

Edited:

A gave the talk I have in mind at a user group in Berlin. Can also go into more technical details if that's preferred. ;)

Slides:
www.slideshare.net/stefanjudis/staying-in-the-fast-lane-tools-to-keep-your-site-speedy-and-light

Video:
youtube.com/watch?v=tV8gfl-DSCI

## Speaker Bio

![](https://avatars1.githubusercontent.com/u/962099?v=3&s=460)

Stefan has been working in e-commerce for 4 years and is just entering the world of single page applications. Mostly doing frontend stuff, he is also really into performance and fancy cutting edge technologies. In his spare time he contributes to various open source projects and maintains the performance tooling collection [perf-tooling.today](http://perf-tooling.today/).

**Comment by KatieK2** [comment]
Hi Stefan, I'm part of the Browser JS talk review committee; thanks for your proposal! It would be helpful to know more about the performance problems you'd identified, and what tools you've used to solve them in your workflow. Thanks!

**Comment by stefanjudis** [comment]
hey @KatieK2 

I gave the talk I proposed recently here in Berlin.

You can check the slides and the recording if you like:

www.slideshare.net/stefanjudis/staying-in-the-fast-lane-tools-to-keep-your-site-speedy-and-light

youtube.com/watch?v=tV8gfl-DSCI

I can go more in detail if that is preferred. :bowtie:

**Comment by KatieK2** [comment]
@stefanjudis Ah, great! I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thanks!

**Comment by stefanjudis** [comment]
@KatieK2 thanks. I updated the issue. :bowtie:
