### ISSUE TITLE
Talk: Using browserify and node streams to power your data visualization apps

### ISSUE THREAD

**Issue by nathanbowser** [cascadiajs/2015.cascadiajs.com#57]
# Using browserify and node streams to power your data visualization apps

* Name      : Nathan Bowser
* Location  : Philadelphia, PA USA
* Email     : nbowser@gmail.com
* Twitter   : [@nathanbowser](https://twitter.com/nathanbowser)
* GitHub    : [nathanbowser](https://github.com/nathanbowser)

## The story you'd like to tell
The biggest tech buzzterm of 2015 is sure to be "full stack engineer". This term exists because there's such a strong separation between client and server. But there are plenty of tools to help alleviate this pain! 

This talk will demonstrate how to combine some of the hottest JavaScript trends: [d3js](d3js.org), [browserify](http://browserify.org/), and node streams to build streaming data visualization apps in the browser.

## Speaker Bio

![](https://avatars1.githubusercontent.com/u/203161?v=3&s=256)

Nathan is the engineer behind [Dash](thedash.com), which is dashboarding software to visualize data. He enjoys using node streams to help remove the server and client dichotomy seen in so many applications. He tries to stay active in the Philly node scene, and enjoys mentoring [node school](http://nodeschool.io/) events.

**Comment by ryan-roemer** [comment]
Hi Nathan -- I'm on the Server JS day talk review committee, and I was wondering if you could flesh out a few more details of what new / interesting / useful things you are doing with D3 / Browserify / Streams? Maybe with a target of helping developers say "why should I use these?"

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. Yes, it would definitely be useful to understand a little more about the takeaways from this talk. Thanks for your proposal!
