### ISSUE TITLE
Talk: Beyond [G[runt|ulp]|Broccoli]: Client-side app builds at scale

### ISSUE THREAD

**Issue by rmurphey** [cascadiajs/2015.cascadiajs.com#61]
# Beyond [G[runt|ulp]|Broccoli]: Client-side app builds at scale

* Name: Rebecca Murphey
* Location: Austin, TX
* Email: rmurphey@gmail.com
* Twitter: [@rmurphey](https://twitter.com/rmurphey)
* GitHub: [rmurphey](https://github.com/rmurphey)
* URL: [rmurphey.com](http://rmurphey.com)

## The Talk

Grunt, Gulp, and Broccoli all got the JS world thinking seriously about how to build and deploy client-side applications, and made the process vastly easier, more repeatable, and more reliable. But what if you need to build and deploy hundreds or thousands of client-side applications every day, each with slightly different rules and considerations, and all relying on services that may or may not be experiencing a hiccup right when you need them?

This is the situation we faced at Bazaarvoice, where each customer gets a custom build of a client-side application for each supported locale, and customers can make changes and redeploy as often as they want. Over two years, our Grunt-based solution became difficult for new developers to understand, difficult to debug, difficult to modify, and extremely fragile when dependencies were feeling flaky. It was also next to impossible to get visibility into why and how often builds were failing.

Starting late last year, we have rewritten our builds from the ground up, with an emphasis on making it as easy as possible for developers to understand, contribute to, modify, and create build workflows. At the same time, we also made it easier to gather metrics about the health and performance of the build system, and made builds vastly more tolerant of dependency failures. In this talk, I'll explain how.

## Speaker Bio

![rebecca-murphey](https://cloud.githubusercontent.com/assets/58987/5961026/4514dce2-a79f-11e4-93f2-0032d11cd964.png)

Rebecca is a staff software engineer at Bazaarvoice, where she leads a team that shepherds third-party JavaScript application development for products with a reach of hundreds of millions of visitors across billions of pageviews. She lives in Austin, TX and writes at rmurphey.com.

**Comment by jasonrhodes** [comment]
Oh, yeah I definitely want to see this. +1

**Comment by jden** [comment]
:+1: This sounds like some great original material from hard-earned experience.

**Comment by othiym23** [comment]
This is very relevant to my interests (and also my job). I would love to see this talk.
