### ISSUE TITLE
Talk: Efficient Web Type, c. 1556

### ISSUE THREAD

**Issue by kennethormandy** [cascadiajs/2015.cascadiajs.com#65]
# Efficient Web Type, c. 1556

* Name      : Kenneth Ormandy
* Location  : Vancouver, Canada
* Email     : hello@kennethormandy.com
* Twitter   : [@kennethormandy](http://twitter.com/kennethormandy)
* GitHub    : [kennethormandy](https://github.com/kennethormandy)
* Url(s)    : [kennethormandy.com](http://kennethormandy.com)

It’s 1556, and Pierre Haultin is punching a completely impractical, metal font: it’s space-efficient typographically, but far too small to read in print.

He intentionally looked for the boundaries type can perform within; we’re still facing dilemmas of typographic efficiency centuries later. Today, web typography must consider measured and perceived performance: their effects influence the reading experience on screens.

This talk shares practical web font performance patterns using JavaScript and CSS, and introduces the new WOFF 2.0 format from a typographic perspective—established by Haultin in the mid-16th century. His experience reveals an overlap between type setting and web performance, relevant to designers’ increasing use of JavaScript, and developers’ of type.

## Speaker Bio

![](https://avatars2.githubusercontent.com/u/1581276?v=3&s=256)

Kenneth Ormandy organises [Type Brigade](http://typebrigade.com), Vancouver’s typography meetup, studies type design at Emily Carr University, and is a designer at [Chloi Inc.](http://chloi.io)

**Comment by mstopham** [comment]
Oh, Kenneth!!
Will he be a speaker for sure? I won't tell. :)
ᐧ

[image: photo]
*Lana*
<http://ca.linkedin.com/in/lanatopham>  <http://twitter.com/MsTopham>

**Comment by kpeatt** [comment]
I've seen this talk before. It's excellent. Highly recommend.

**Comment by KatieK2** [comment]
Ha! Looks like I'm going to see this at the end of the month! ;)

**Comment by kennethormandy** [comment]
It would seem that way hah! Looking forward to seeing you there. :koala:

**Comment by misscs** [comment]
Oh, goodie. Glad I get to see this at CSSConf AU
