### ISSUE TITLE
Talk: Abstraction and the new challenges with teaching ES6

### ISSUE THREAD

**Issue by ashleygwilliams** [cascadiajs/2015.cascadiajs.com#73]
# Abstraction and the new challenges with teaching ES6

* Name: Ashley Williams
* Location: Brooklyn, NYC, USA
* Email : ashley@bocoup.com
* Twitter: [@ag_dubs](https://twitter.com/ag_dubs)
* GitHub: [ashleygwilliams](https://github.com/ashleygwilliams)

# what?
javascript programming language design from an educational perspective as told by Jacques Derrida, Richard Feynman, Pablo Picasso, and Carl Sagan (among others)

The new ES6 standard introduces several new abstractions- through my experience as an educator I’ve seen abstractions thwart - not help! - new students of programming. This talk aims to explore the difficulties beginners experience with abstractions, with specific examples from ES6, and then present new ideas on alleviating those difficulties. This talk will also present a strong opinion on what types of abstractions are best for both the new and the advanced developer, from within a framework established by figureheads from the sciences and humanities.

# why me?

![bio_pic](https://en.gravatar.com/userimage/33260083/3f9e034fb4232440aa226198b409bae5.jpg?size=256)

Formerly a NYC Teaching Fellow, my career arc tracks from middle school science teacher to web developer. A self-taught programmer with a background in philosophy and neuroscience, I've always been an advocate of the well-rounded developer from a non-CS background. Since transitioning from public education to the world of technology, I've made it my aim to deeply interrogate how we as a community teach ourselves and the next generation of web developers. And while computer science education is an increasing en vogue topic, with many players and perspectives, I've found that my interdisciplinary approach is unique and engaging-- which makes it more approachable to a wider audience.

Ashley is currently an Open Web Engineer at [Bocoup](http://www.bocoup.com), where she focuses on pedagogy and building educational products for teaching both the beginner and advanced student how to be an awesome, productive member of the web development community.

# czech it out
This repo holds the slides to the talk I'd like to modify and give at CascadiaJS, each branch is a modified instance for the audience I delivered it to: https://github.com/ashleygwilliams/how-to-train-your-programmer

I've given variations of this talk at 2 universities and the BostonJS meetup, but would really like the opportunity to give it at a large conference. The need for industry professionals, regardless of their role, to approach JS from an educational perspective is only growing. I think my talk does a good job of encouraging people at any level of skill that they have a role in improving JS education, whether it is working on building new abstractions for the language through TC-39 or as a someone who is just starting out.  I'm super open to feedback on the content and modifying it to best fit CascadiaJS!

**Comment by othiym23** [comment]
This sounds neat!

**Comment by KatieK2** [comment]
Hi @ashleygwilliams, I'm part of the Browser JS talk review committee. This is very cool sounding proposal!. It would be helpful to understand the timeframe that you're envisioning for this talk; for example, is it around around standard talk length (25m) or is it more like a workshop?
I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thank you for your proposal!
