### ISSUE TITLE
Talk: Using statecharts for clean & scalable UX

### ISSUE THREAD

**Issue by thure** [cascadiajs/2015.cascadiajs.com#74]
# Using statecharts for clean & scalable UX

* Name      : Will Shown
* Location  : Seattle
* Email     : w@willshown.com
* Twitter   : [@wwwillshown](https://twitter.com/wwwillshown)
* GitHub    : [thure](https://github.com/thure)
* Url(s)    : [willshown.com](http://willshown.com/)

## The what, why, and how of statecharts in JavaScript

Statecharts are awesome. They’re so much more than ‘state’ in Ember.js or React, and they can be used in conjunction with any framework. Using statecharts you can translate interaction designs directly into code that runs on the browser or in Node (or even in embedded systems).

Because statecharts are such a fantastic way to discretize user input into useful transitions between an app’s views, I’ll focus chiefly on how to develop with statecharts for the front-end. The talk will include a description of designing with statecharts, translating those designs to [SCXML](http://www.w3.org/TR/scxml/) (or the new SCJSON), and working with [SCION](https://github.com/jbeard4/scion) in an example app.

## Speaker Bio

<img src="http://i.imgur.com/A0KbLDwl.jpg" width="256" title="Will Shown’s head" />

Hello, CascadiaJS! I’m Will Shown, a UX designer and front-end web developer. I’ve been working with the connection between browsers and humans since building my first web app in 2008 while learning Cognitive Science at McGill University.

Since then I’ve been part of the team that redesigned [MSN.com](http://www.msn.com/) and started a sci-fi game engine called [GEOF](https://github.com/G-E-O-F/). I’m an avid fan of RuPaul’s Drag Race and my favorite weather is fog.

**Comment by jbeard4** [comment]
+1

**Comment by ryan-roemer** [comment]
Hi Will -- I'm on the Server JS day talk review committee. I was hoping to have a little bit more about the details about statecharts in your abstract as pertains to JS / implementation for us? Maybe some links or a brief description?

**Comment by thure** [comment]
Sure! In JS, statecharts are interpreted with [SCION](https://github.com/jbeard4/scion) (link is also in the description), both in browsers and in Node. The [readme for SCION](https://github.com/jbeard4/SCION/blob/master/README.md) has a great introduction to getting started.

I've also been writing tutorials for SCXML – they can be found in my [scxml-tutorials](https://github.com/thure/scxml-tutorials) repository.
