### ISSUE TITLE
Talk: Good, fast and cheap: putting performance back in the equation

### ISSUE THREAD

**Issue by imurchie** [cascadiajs/2015.cascadiajs.com#77]
* Name      : Isaac Murchie
* Location  : Oakland, USA
* Email     :  isaac@saucelabs.com
* Twitter   : [@imurchie](https://twitter.com/imurchie)
* GitHub    : [imurchie](https://github.com/imurchie)

## Once upon a time...

As the old development adage goes, of good, fast and cheap (or on-time, inexpensive and performant) you can choose two. Too often good and cheap, on-time and inexpensive, are chosen at the expense of application performance. Only later do we realize that what we've built needs to be fast as well. But early choices can make it difficult to improve performance later on, and, to make matters worse, when we do get around to worrying about being fast we often find we are past the point of Apps Too Big To Change™.

So as application developers we ought to be thinking about performance early and often. We need to be aware of how our decisions can affect how well our applications run. This talk will introduce the topic of analysis, taking applications as the basis and showing some techniques for drilling down to identify and solve issues.

This talk will cover:

- motivation - isn't performance something for sysadmins to worry about?
- terminology - so wow, very words, such meaning.
- some useful methodologies - top-down analysis of workload

After this talk, audience-members will hopefully have a new perspective on building their applications. At the very least they ought to have under their belts a few tools for tackling the challenge of beginning analysis of performance issues in JavaScript applications.

## Speaker Bio

![](https://raw.githubusercontent.com/imurchie/imurchie.github.io/master/avatar.jpg)

Isaac works on test automation frameworks, has a PhD in Sanskrit literature, and loves binder clips.

**Comment by KatieK2** [comment]
Hi, I'm part of the Browser JS talk review committee. This is an interesting proposal! It would be helpful to understand how you've decided on the tools and workflows you'll recommend; IE do they come from problems in your projects?
FYI, I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thanks!
