### ISSUE TITLE
Talk: Static Type Checking in Javascript

### ISSUE THREAD

**Issue by bsiddiqui** [cascadiajs/2015.cascadiajs.com#79]
# Static Type Checking in Javascript

* Name: Basil Siddiqui
* Location: San Francisco, CA, USA
* Email: basil.siddiqui@gmail.com
* Twitter: [@_bsiddiqui](https://twitter.com/_bsiddiqui)
* GitHub: [bsiddiqui](https://github.com/bsiddiqui) and [enjoy](https://gitub.com/enjoy)
* Medium: [bsiddiqui](https://medium.com/@bsiddiqui)

## The story you'd like to tell
We all love how fast, simple to use, flexible, and expressive Javascript can be. Given some of Javascript's quirks, however, the weak type system can create some issues: some bugs can be difficult to find, readability is worse because dependencies aren't explicit, etc. 

There are a few different options to apply static type checking so that we can still use Javascript but get some of the benefits static type checking provides. This talk will dive into those options, when it makes sense to use them, and when it doesn't. The goal of the talk is to explain how we can add static types to Javascript without disempowering the dynamism that makes it great.

## Talk outline
A) Static typing versus dynamic typing
* quickly discuss differences

B) Why we need static type-checking with live examples
* catching early errors at compile time vs. in unit tests (silent type conversions, null dereferences, etc)
* speed of development
* code documentation
* team collaboration
* usability for programmers coming from static languages
* auto-completion in IDEs

C) Options for static typing (key differences with examples)
* Microsoft TypeScript
* Facebook Flow
* Google AtScript

D) What the future has in store
* future code intelligence based on static typing

## Speaker Bio
![screen shot 2015-01-30 at 4 48 05 pm](https://cloud.githubusercontent.com/assets/2721959/5983961/d15704fe-a89f-11e4-8fb3-41a6cba587fe.png)

Basil is a full-stack software engineer that specializes in API development and application infrastructure. Most recently he worked as an engineer at Lob and as a Hacker in Residence at SFIncubator. Since then he has left to work full-time on a project, Hi Bryce, that is an AI-based administrative assistant.

**Comment by jden** [comment]
I'm interested in this! Also, @bsiddiqui, let me know if you want to get together in SF to talk about typed javascript :)

**Comment by bsiddiqui** [comment]
@jden yeah let's do it! I'll shoot you an email

**Comment by bsiddiqui** [comment]
@KatieK2 think this could be a talk on ServerJS Day as well since it can be used for the browser or server :)

**Comment by ryan-roemer** [comment]
@bsiddiqui -- I'm on the Server JS day talk review committee and I was wondering if you could enumerate a few of the options for us here in the abstract as well as the benefits? Thanks!

**Comment by bsiddiqui** [comment]
@ryan-roemer sorry just saw this notification! Will update the description today :)

**Comment by bsiddiqui** [comment]
Hey @ryan-roemer! Updated the abstract to mention the options I'll talk about as well as some of the benefits. Let me know if you need any more info from me

**Comment by bsiddiqui** [comment]
Hey @ryan-roemer are there any updates on this? I noticed that some speakers have been added to the site. Have all speakers been finalized?
