### ISSUE TITLE
Readme for "Free Ideas"

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2015.cascadiajs.com#84]
I propose a new directory within /proposals called "free_ideas". The README.md for this directory explains its purpose:

------------------------------

#Free Ideas

This directory contains "free ideas" to help you get started on your speaking proposal for Cascadia JS. Feel free to take one of these starter ideas, give it a good hard stare and punch it up a little, and then submit a talk to our CFP: [https://github.com/cascadiajs/2015.cascadiajs.com/blob/master/proposals/README.md]

Remember: "Great talks are about ideas + the person + execution." 

The talk selection committees may not choose any talks on these topics. Because these very ideas are free for all, the committees could expect a talk based on these free ideas to be among the most well defined proposals submitted.

##Why?

These ideas will help increase submissions to our conference by giving prospective speakers some starting ideas to riff on. Additionally, the entire Cascadia developer community can contribute rough drafts of talks they'd like to see attend.

------------------------------

Comments appreciated! If useful, I can make a pull request adding this directory and readme.

**Comment by othiym23** [comment]
:+1: I have 3 or 4 things I could put in there, were this to exist.

**Comment by jden** [comment]
Sounds good - go ahead and create a PR :)

**Comment by KatieK2** [comment]
@othiym23 :D You were the first person I was going to ask for more ideas once ready.
@jden Thanks! Will do, probably Mon or Tues so everyone has a chance to comment. :)

**Comment by alexlande** [comment]
Resolved by #108.
