### ISSUE TITLE
Talk: Optimizing Data Workflows in React

### ISSUE THREAD

**Issue by amoskyler** [cascadiajs/2015.cascadiajs.com#86]
# Optimizing Data Workflows in React

* Name      : Amos Kyler
* Location  : San Francisco, USA
* Email     : amos@wearefractal.com
* Twitter   : [@aokyler](https://twitter.com/aokyler)
* GitHub    : [amoskyler](https://github.com/amoskyler)
* Url(s)    : [amoskyler.com](http://amoskyler.com) [wearefractal.com](http://wearefractal.com)

## The story you'd like to tell

Since it's release in 2013, React has caused a lot of stir in the javascript world. While it excels as a front-end rendering engine, it's unopiniated stance on data patterns leaves developers to find their own solutions. In this talk you will see real world examples with pros, and cons in a survey of various React data patterns. Topics covered include Relay, Backbone/Ampersand models, Flux and how you can solve the M in the React-MVC puzzle.

## Speaker Bio

![Amos Kyler - amoskyler.com](http://www.amoskyler.com/logo)

Software engineer @ Fractal Building a better world for developers -- today.

**Comment by mdressman** [comment]
+1, are you planning on diving into various Flux implementations?
