### ISSUE TITLE
Talk: How to Win Friends and Influence Developers

### ISSUE THREAD

**Issue by benedmunds** [cascadiajs/2015.cascadiajs.com#89]
# How to Win Friends and Influence Developers

* Name      : Ben Edmunds
* Location  : Seattle, WA, USA
* Email     : ben.edmunds@gmail.com
* Twitter   : [@benedmunds](	)
* GitHub    : [benedmunds](http://github.com/benedmunds)
* Url(s)    : [benedmunds.com](http://benedmunds.com)

## The story you'd like to tell

Learn how to get along well with your co-workers and work your way up the corporate ladder. Or better yet, burn it down. Politely of course.

In this session we will lay out several soft skills for developers

Working well with your co-workers.
How to look good in the eyes of management without giving up your opinion or dignity.
Basic pointers for leading other developers.
How to get involved and excel at open source projects.

## Speaker Bio

![](https://secure.gravatar.com/avatar/22f21d5c22b930fd35dd98f25dedf6a4)

CTO of an awesome company you've never heard of by day, hacking on crazy ideas by night. PHP Town Hall podcast co-host. CodeIgniter Steering Committee member. Author. Speaker. Open Source Advocate.

**Comment by blakmatrix** [comment]
:+1:
