### ISSUE TITLE
Big Mess: Organizing CSS in the World of Preprocessors

### ISSUE THREAD

**Issue by ncksnydr** [cascadiajs/2015.cascadiajs.com#90]
# Big Mess: Organizing CSS in the World of Preprocessors

* Name      : Nick Snyder
* Location  : Seattle, WA
* Email     : nick@nicksnyder.is
* Twitter   : [@_nicksnyder](https://twitter.com/_nicksnyder)
* GitHub    : [ncksnydr](https://github.com/ncksnydr)
* Url(s)    : [NickSnyder.is](http://nicksnyder.is)

## The story you'd like to tell

With this presentation, I plan to present a series of tips, tricks, and team-building methods for keeping your CSS organized, consistent, and maintainable in the Sass/LESS/Stylus world of preprocessors. 

## Speaker Bio

![oh hai](https://avatars2.githubusercontent.com/u/839061?v=3&s=460)*avatar is required*

Nick Snyder was born on a cold February afternoon in 1986. When the doctor took one look at him, he grinned and said, “This kid is destined for great things.” Not really…but Nick likes to think that happened. In Kindergarten he was sketching; by 7th grade he was coding. Ever since, Nick possessed the rare talent of combining design with development. He’s passionate about responsive web design, beautiful colors, and all things typography.

Currently, Nick runs his own design and web development practice based in beautiful Seattle, WA. He boasts a healthy client resume that includes the NFL, The New England Journal of Medicine, ESPN, Humana, Aetna, John Hancock, ZirMed, and Intuit.

Nick does more than just play with pixels: Nick’s vices include long-distance running, bourbon, the Philadelphia Phillies, animated GIFs, the Legend of Zelda, and a forbidden love with a hammock in Cape May, NJ—did we mention that he’s an adult?

**Comment by alexlande** [comment]
Hi @ncksnydr, thanks for submitting!

I'm intrigued, but it might be helpful to elaborate on the subject a little bit more in your proposal. In particular, it would be nice to get a better sense of whether your talk will deal with things like automated tooling, coding conventions, team process, other things, all of the above?

**Comment by ncksnydr** [comment]
Hey @alexlande,

I apologize for not being clear. My goal is to present how to best organize CSS in a project that uses a preprocessor—which can get unruly very quickly because of all the features it provides. I want to show the audience how to harness those features to write cleaner, clearer code through techniques like breaking the stylesheet into several parts, taking advantage of variables and mixins, separating machine written from human written code, flag levels of documentation, and basic CSS organization techniques like alphabetizing your properties. 

Does that make things a bit more clear?

--Nick

**Comment by alexlande** [comment]
Thanks @ncksnydr, that definitely helps. You may want to update the body of your proposal with that context, as the committee won't be reading the comments here during the review process.
