### ISSUE TITLE
Hacks for Snacks

### ISSUE THREAD

**Issue by iammerrick** [cascadiajs/2015.cascadiajs.com#92]
# Hacks for Snacks - Teaching & Feeding Kids

* Name      : Merrick Christensen
* Location  : Utah, USA
* Email     : merrick.christensen@gmail.com
* Twitter   : [@iammerrick](http://twitter.com/iammerrick)
* GitHub    : [iammerrick](http://github.com/iammerrick)
* Url(s)    : [merrickchristensen.com](http://merrickchristensen.com)

## Hacks for Snacks

I want to tell the story of [Hacks for Snacks](http://hacksforsnacks.com). Hacks for Snacks is a community outreach program that helps get kids excited about programming while feeding their less privileged peers. We host events that kids how to code using Spheros, Drones and Arduinos with JavaScript. Developers lead a team of kids in a set of robotics programming challenges we created.  I want to tell the story of getting Hacks for Snacks up and running, ask for help from the community, and encourage people to start their own Hacks for Snacks using our challenges or to get involved in other outreach program.

## Speaker Bio

![Merrick Chrsitensen ](http://cl.ly/image/0i0Q270p2U3u/avatar.jpeg)

I am a kind chap hoping to impact the world for good. I'm an open source contributor. Occasional podcast visitor (JSJabber, ng-air, Shoptalk Show). Conference organizer (ng-conf). And Domo employee.

**Comment by JakeLingwall** [comment]
+1 Merrick is a kind chap and Hacks for Snacks deserves the publicity.
