### ISSUE TITLE
TALK: Implementing a visual CSS testing framework

### ISSUE THREAD

**Issue by jessicard** [cascadiajs/2015.cascadiajs.com#94]
# Implementing a visual CSS testing framework

* Name      : Jessica Dillon
* Location  : San Francisco, CA, USA
* Email       : jessicard@mac.com
* Twitter     : [@jessicard](http://www.twitter.com/jessicard)
* GitHub    : [jessicard](http://www.github.com/jessicard)
* Url(s)    : [http://jessicard.com](http://jessicard.com)

## The story you'd like to tell

Working with large CSS codebases can be hard. Large-scale refactors, or even just tweaking styles on our more general elements, could end up having unintended consequences on the rest of the site. To catch these problems, we manually check every page on our site, which is a slow and error-prone approach. We need a better way to test our CSS. This talk will walk through how we implemented a visual CSS testing framework using RSpec & Selenium, using automatic screenshot comparison to catch style regressions.

Blog post: https://bugsnag.com/blog/implementing-a-visual-css-testing-framework/
CSSConf Oak 2014 Slides: http://www.slideshare.net/jessicardillon/implementing-a-visual-css-testing-framework.

## Speaker Bio

![](https://pbs.twimg.com/profile_images/557025986223411201/8ZXrxVdG.jpeg)

Jessica is a self taught full-stack software engineer in the heart of San Francisco. She works at Bugsnag, the leading real-time crash detection service for mobile and web applications. Her expertise runs the gamut from developing rich in-browser applications to building service-oriented backends. When not coding or playing games, she likes to hang out with her dog named Boo.

**Comment by jefflembeck** [comment]
I very much want to see this one.

**Comment by misscs** [comment]
:wave: will you be expanding or changing the talk in any way from the version at cssconfoak?
