### ISSUE TITLE
Code of Conduct sms reporting app

### ISSUE THREAD

**Issue by davethegr8** [cascadiajs/2015.cascadiajs.com#97]
As part of the 2015 conference, I'd like to build out a simple SMS reporting application.

The Sounders/Seahawks have a number (HAWK12) you can text during a game to report any disruptive / unruly behavior. Stadium staff then message back to gather more information (seat location, description of offender), and dispatch ushers/security to take care of the problem. In my experience, this is an extremely helpful tool, and I'd like to bring it to CascadiaJS.

It works like this:

* Anyone can send a message to the SMS number.
* When new messages are received, the app automatically replies and sends the message to all organizers
* Organizers can either ACCEPT or DECLINE (if they are busy) taking the report.
* Once an organizer accepts a report, all SMS messages from the reporter are delivered to the organizer, and messages from the organizer are sent to the reporter.
* When the report has been completed, the organizer replies back CLOSE and they are freed up to handle another report.

**Comment by nvcexploder** [comment]
I like it. Should there be a way to let folks know that there's a problem, and then have the person who is going to respond be the only person to receive the info on the incident?

**Comment by davethegr8** [comment]
By "folks" are you referring to staff? This would be like a first line reporting system that feeds into the COC_REPORTING.md process. Whomever is available should respond ASAP, and then depending on the situation gather other staff as needed.

**Comment by nvcexploder** [comment]
So when the person sends the initial report, staff is notified. Somebody says they can take it, and then can go and view the report?

**Comment by kennethormandy** [comment]
This is a really great idea, even better if you can build it out as something reusable outside of CascadiaJS. We’d definitely be into trying something like this for [the typography meetup](http://typebrigade.com) in Vancouver—obviously meetups are way smaller, but consolidating phone numbers and knowing every organiser can get the message is super valuable anyway. Slack integration sounds great too.

Let me know if you need a beta tester, I’d definitely be interested and have events to use it for well in advance of the conference.

**Comment by davethegr8** [comment]
@nvcexploder It's probably best to use as a less-formal process. We want everyone to feel comfortable using this, so we'll have a range of responses, depending on the circumstances.

```
>>> From:555-1111 There was a weird sketchy guy hanging out at the bar who didn't have a conference badge.
<<< To:555-1111 Thanks, we'll check it out! For identification purposes, what was he wearing?
>>> From:555-1111 Red jacket, tattered blue sweats, and a dirty baseball hat
```

Or perhaps

```
>>> From:555-2222 There's an extremely drunk woman in the pool area who is saying all kinds of terrible things, and it's really bothering my kids. We got so offended we had to leave.
<<< To:555-2222 Thanks, we'll check it out! Can you meet me in the Green Room so I can get a more detailed report?
>>> From:555-2222 Of course, we are on the way now.
```

Does that make sense? Happy to chat in slack more, I'm not sure I'm describing it well.

@kennethormandy It'll definitely be as reusable as I can make it.

**Comment by davethegr8** [comment]
Examples with images!

![screen shot 2015-02-02 at 5 51 31 pm](https://cloud.githubusercontent.com/assets/55392/6013078/96e0a674-ab04-11e4-8f04-c09d2df9143c.png)
![screen shot 2015-02-02 at 5 54 16 pm](https://cloud.githubusercontent.com/assets/55392/6013079/98db9bf0-ab04-11e4-8e3f-ea5966cb1d1e.png)

**Comment by bryan-m-hughes** [comment]
If it's any help, we have something kinda like this implemented for NodeBots SF already. Code is at https://github.com/bryan-m-hughes/incident-reporter, and our CoC is at https://github.com/nodebots/sf/blob/master/coc.md.

We use Twilio as the telephony service, and they gave us a comped account for this purpose.

**Comment by hackygolucky** [comment]
wow, thanks @bryan-m-hughes 

Really great work so far, @davethegr8 This is an awesome step forward in our attendees trusting we're watching out for them and backing it up with a tool to follow through with incidents.

**Comment by davethegr8** [comment]
ditto @bryan-m-hughes :) that's very helpful to have as a reference. Thanks!

**Comment by davethegr8** [comment]
Testable version of this is ready.

**Comment by davethegr8** [comment]
Revised to use TaskRouter. Establishes a 1:1 relationship between individual report and staff handling the report.

Should include: 
* some way to save state
* reminder to close tasks
